(()=>{
'use strict';
const categories=[
 {name:'地漏',volume:2497,unique:2264,risk:31.3,dup:10.9,themes:[['质量做工',946,48.5],['颜色外观',565,28.9],['效果性能',251,12.9],['安装施工',231,11.8]],job:'用户购买的核心不是“一个金属件”，而是同时解决快速排水、隔绝返味、拦截毛发和适配洗衣机排水。',positive:'厚重用料、边缘无毛刺、隐形外观、开合顺畅和安装尺寸标准最容易建立品质信任。',pains:['排水速度与防臭芯阻力发生冲突，拿掉芯能排水但会返味。','表面蜕皮、掉色、磕碰等问题直接破坏“高价大品牌”的预期。','客服对三通、负压和安装适配解释不清，放大产品问题。'],scenes:'卫生间淋浴、阳台洗衣机、老房返味治理；使用后评价比开箱评价更关键。',action:'按地漏芯类型建立“流量—防臭—管径”适配表；详情页给出排水量、安装深度和错误安装示例；售后增加视频诊断。',quote:'“地漏芯洗澡水排不出去，溢出来；客服让拿掉芯，拿出来不就反味了。”',quoteMeta:'产品性能 + 安装指导'},
 {name:'艺术漆',volume:1592,unique:1516,risk:23.3,dup:6.9,themes:[['效果性能',522,33.5],['颜色外观',386,24.7],['气味环保',294,18.8],['安装施工',199,12.8]],job:'主要任务是低成本完成瓷砖、卫生间或旧墙改色，让普通用户也能DIY出“翻新前后明显”的效果。',positive:'覆盖力、颜色高级、低气味、工具齐全、薄刷操作简单，是评论中最具传播力的组合。',pains:['实际颜色与展示图不一致，二次补购还可能出现批次色差。','起皮、翘壳、变色常与基层处理、干燥时间和罩面步骤混杂。','“新手可操作”与实际施工复杂度之间存在落差。'],scenes:'老旧卫生间翻新、瓷砖改色、租住空间轻改造和DIY小花砖。',action:'把基层材质、处理剂、薄刷次数、间隔时间和罩面要求做成场景化施工卡；提供实体色板与批次管理说明。',quote:'“图片依次是原来的地面、一遍、两遍和DIY小花……客服因运输问题很快解决，也适合新手操作。”',quoteMeta:'DIY场景 + 服务补救'},
 {name:'水槽套餐',volume:2312,unique:2239,risk:9.6,dup:3.1,themes:[['质量做工',892,48.6],['颜色外观',667,36.3],['安装施工',404,22.0],['客服售后',322,17.5]],job:'用户需要的不只是水槽，而是一套能与台面、净水器、洗碗机和水龙头协同安装的厨房工作站。',positive:'304不锈钢、盆体深度、抗指纹、抽拉龙头、集渣篮和配件齐全共同形成“一站式配齐”的价值。',pains:['左右开孔、净水器孔和实物不一致，往往安装后才发现，返工成本高。','套餐配件多，少件、错件或接口不适配会阻断安装。','开箱未验货与跨城市装修使责任认定更复杂。'],scenes:'新房整装、旧水槽替换、净水器/洗碗机联动安装；安装师傅是重要影响者。',action:'下单前用结构化问答确认台面尺寸、开孔方向和设备接口；包装内放置配件清单；安装前强制开箱核对。',quote:'“第一句话就说明净水器孔要在左边，客服推荐后实物却只有右边一个孔，安装后才发现。”',quoteMeta:'配置错误 + 高返工成本'},
 {name:'内墙乳胶漆',volume:1968,unique:1890,risk:11.3,dup:4.7,themes:[['气味环保',618,36.5],['客服售后',422,25.0],['颜色外观',371,21.9],['效果性能',307,18.2]],job:'用户希望在颜色翻新的同时降低气味和入住等待，并获得用量测算、上门施工或完整刷新服务。',positive:'低气味、颜色准确、遮盖和耐擦洗是产品认可点；专业师傅、进度透明和无增项则是服务认可点。',pains:['“8小时入住”与热线解释不一致，环保承诺容易演变为信任危机。','色卡、屏幕展示和上墙干燥后的颜色存在认知差异。','墙体原有发霉、开裂与产品施工效果常被混在同一条评论中。'],scenes:'儿童房/老人房刷新、旧墙修复、整屋服务和局部补漆。',action:'统一入住时间口径并说明检测条件；把旧墙诊断与漆本身效果分开；提供小样试刷和分墙体用量计算。',quote:'“买之前说8小时能入住，热线又说7天后才能入住，有明显误导。”',quoteMeta:'环保承诺 + 服务一致性'},
 {name:'环氧漆(地坪漆)',volume:4645,unique:4294,risk:17.1,dup:8.6,themes:[['效果性能',788,28.1],['安装施工',519,18.5],['客服售后',471,16.8],['质量做工',436,15.6]],job:'用户想以可控预算完成车库、车间、水泥地面翻新，并获得平整、耐磨、易清洁的长期效果。',positive:'刷涂顺手、颜色均匀、地面焕新和客服施工指导，会明显提升完成感。',pains:['标称每公斤施工面积与实际消耗差异，导致中途补货和二次人工费。','两次补购产生批次色差，整片地面难以修复。','起泡、起皮、翘壳与基层含水率、配比和施工温度高度相关。'],scenes:'车库、仓库、工厂车间和自建房水泥地；施工连续性要求高。',action:'按基层粗糙度提供用量区间而非单点承诺；同项目锁定批次；增加含水率、配比、可使用时间和养护说明。',quote:'“10平方米第一次买15公斤不够，补买后同色号色差很大，还多付了二次人工费。”',quoteMeta:'用量承诺 + 批次色差'},
 {name:'密封条',volume:1398,unique:1275,risk:18.5,dup:12.7,themes:[['效果性能',308,31.5],['质量做工',194,19.9],['安装施工',123,12.6],['物流包装',103,10.5]],job:'用户希望用低成本解决门窗漏风、噪声、灰尘和老化发黄问题，同时不影响关门。',positive:'胶条厚实柔软、粘贴牢、静音防风和送助粘剂，是效果得到确认的关键。',pains:['厚度选择错误会出现“太厚关不上、太薄仍漏风”。','背胶难撕、粘性不足或残留气味使安装体验下降。','手撕分层结构虽然通用，但用户难准确判断保留厚度。'],scenes:'入户门漏风、窗框密封、老旧胶条替换和卧室降噪。',action:'提供缝隙测量工具和1:1厚度卡；按门窗类型推荐规格；安装说明加入清洁、助粘和固化时间。',quote:'“门缝不大的不要买这种手撕款，撕厚了不好关门，撕薄了又进风。”',quoteMeta:'尺寸适配 + 安装决策'},
 {name:'外墙乳胶漆',volume:1297,unique:1214,risk:14.9,dup:10.0,themes:[['颜色外观',308,27.2],['效果性能',260,22.9],['物流包装',189,16.7],['质量做工',157,13.9]],job:'用户需要对阳台、天井和外墙水泥面进行防水、美化与耐候翻新。',positive:'水泥面可施工、纹理效果明显、防水和客服工艺指导是主要认可点。',pains:['雨后掉色、掉粉等耐候问题会迅速否定产品价值。','颜色氧化、白色发黄与色差的责任难界定。','少发工具或小包装会打断施工，客服拖延使问题升级。'],scenes:'阳台、天井、围墙和农村自建房外立面，常由用户或普通师傅施工。',action:'详情页区分底漆/面漆/罩面并强调天气窗口；增加耐候测试说明；施工套装按购买桶数配足工具。',quote:'“刷完24小时后下雨就像洗煤球一样掉黑色，商家还推脱责任。”',quoteMeta:'耐候性能 + 售后归责'},
 {name:'瓷砖胶',volume:1356,unique:1298,risk:14.1,dup:8.7,themes:[['质量做工',257,19.0],['物流包装',229,16.9],['效果性能',210,15.5],['客服售后',193,14.3]],job:'用户希望选到适配大砖、墙砖和不同基层的粘结系统，避免空鼓脱落。',positive:'双组份、粘性强、师傅认可和品牌信任构成主要购买理由。',pains:['大包装运输破损，退货运费高，线上购买风险突出。','液体背胶与双组份产品适用场景容易混淆。','用量、砖尺寸、基层和施工方法未形成清晰匹配。'],scenes:'全屋装修、大砖上墙、防水后贴砖；瓦工意见对购买影响显著。',action:'按砖尺寸/吸水率/基层建立选型矩阵；大包装加强防破损；下单前展示退换货成本和本地补货方案。',quote:'“多袋运输都有破损，退货运费特别贵；这种大东西还是实体店买更省心。”',quoteMeta:'物流破损 + 退货成本'},
 {name:'腻子',volume:995,unique:913,risk:16.8,dup:14.4,themes:[['效果性能',186,19.3],['物流包装',128,13.3],['质量做工',125,12.9],['气味环保',103,10.7]],job:'用户多用于小面积补坑、遮盖涂画、旧墙修复，希望开罐即用并与原墙颜色接近。',positive:'容易涂抹、补坑后平整、低成本修复小面积墙面是核心价值。',pains:['用户把腻子、底漆和面漆功能混淆，直接覆盖可能导致脱落。','难打磨、遮盖不足和色差在局部修补中格外明显。','产品有效期与开封使用条件容易被忽略。'],scenes:'儿童涂画遮盖、粘钩坑修补、出租房局部翻新和小面积发霉修复。',action:'按“补坑/找平/改色”拆分产品用途；提供三步修复路径；标明与旧墙颜色难完全一致并建议扩大收口。',quote:'“直接盖漆后墙皮脱落，师傅说应该先铲除，再做底漆和面漆。”',quoteMeta:'用途误解 + 施工路径'},
 {name:'毛巾架',volume:1262,unique:1205,risk:11.9,dup:5.7,themes:[['质量做工',399,44.9],['颜色外观',355,39.9],['安装施工',199,22.4],['客服售后',90,10.1]],job:'用户要在潮湿、空间有限的卫生间增加收纳，同时避免打孔并保持装修风格统一。',positive:'枪灰色质感、折叠省空间、承重稳和免打孔安装方便是高频亮点。',pains:['免打孔胶粘不牢存在坠落和砸伤风险，是安全问题而非普通差评。','墙面材质和潮湿程度影响粘贴，但详情页往往缺少限制。','安装失败后商家拒绝承担打孔或修复成本。'],scenes:'小户型卫生间、瓷砖墙面、租房免打孔和折叠收纳。',action:'将承重测试、墙面适配和固化时间置于首屏；高负载产品优先推荐打孔；建立坠落事故快速处理流程。',quote:'“按照说明架子无法粘住，家里没人时砸在马桶上；如果有人可能会受伤。”',quoteMeta:'安装安全 + 宣传边界'},
 {name:'角阀',volume:1138,unique:1061,risk:10.3,dup:8.3,themes:[['质量做工',345,49.3],['颜色外观',143,20.4],['安装施工',117,16.7],['效果性能',57,8.1]],job:'角阀属于隐蔽工程，用户购买的是长期不漏水、开关顺滑和后期可检修的安全感。',positive:'全铜分量、陶瓷阀芯、电镀做工、冷热标识和加长螺纹是信任线索。',pains:['个别到货即坏或安装后漏水会严重打击品牌信任。','“全铜”“黄铜”“陶瓷芯”等材料表达容易引发预期差异。','尺寸、墙砖厚度和装饰盖适配影响安装效果。'],scenes:'全屋水路安装、马桶/热水器接水和旧阀更换，安装师傅意见重要。',action:'公开主体材质和阀芯测试；包装增加压力测试标识；按贴砖厚度提供螺纹长度选择。',quote:'“买两个角阀坏一个，这种隐蔽工程配件品控差会让人非常不放心。”',quoteMeta:'品控 + 用水安全'},
 {name:'金属漆',volume:1016,unique:970,risk:17.8,dup:5.3,themes:[['物流包装',149,21.6],['质量做工',142,20.5],['效果性能',118,17.1],['颜色外观',118,17.1]],job:'用户希望省去复杂除锈和打磨，把暖气、铁门、彩钢瓦或金属家具快速翻新。',positive:'水性低味、直接刷、附送工具、覆盖旧锈和改色明显是主要吸引力。',pains:['“免打磨除锈”容易被理解为无需任何基层处理，导致附着力争议。','标称喷涂面积与实际用量不一致。','桶装运输漏液和工具丢失影响开工。'],scenes:'暖气背篓、铁艺家具、防盗门、彩钢瓦和户外金属设施。',action:'按锈蚀等级说明需要的打磨程度；给出刷涂/喷涂用量差异；桶盖增加二次密封并把工具独立包装。',quote:'“喷不到介绍的面积，桶里像只有多半桶；后来又从别处补买，工具也在运输中丢了。”',quoteMeta:'用量 + 包装履约'}
];
window.REVIEW_INSIGHTS=categories;
return;
const fmt=n=>n.toLocaleString('zh-CN');
let selectedCategory=0;
let selectedMonth='全部时间',selectedShop='全部店铺',selectedTheme=0;
const filterData={months:[],categories:{}};
let dataManifest=null;
const categoryLoads=new Map();
const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function getCategoryFilter(c){return filterData.categories[c.name]||{shops:[],segments:{}}}
function getSegment(c){const data=getCategoryFilter(c);return data.segments[`${selectedMonth}|${selectedShop}`]||data.segments[`${selectedMonth}|全部店铺`]||data.segments['全部时间|全部店铺']}
function displayCategory(c){const segment=getSegment(c);return{...c,themes:c.themes.map(t=>{const d=segment?.themes?.[t[0]];return[t[0],d?.count||0,d?.rate||0]})}}
function availableShops(c){const data=getCategoryFilter(c);return data.shops.filter(shop=>data.segments[`${selectedMonth}|${shop}`])}
function brandRows(c){const data=getCategoryFilter(c);return data.shops.map(shop=>{const x=data.segments[`${selectedMonth}|${shop}`];return x?{shop,...x}:null}).filter(Boolean).sort((a,b)=>b.score-a.score||b.n-a.n)}
const labels=(items,fallback='未形成集中信号')=>items?.length?items.map(x=>x[0]).join('、'):fallback;
const signalRows=items=>items?.length?items.map(x=>`<div class="signal-row"><span>${esc(x[0])}</span><span>${fmt(x[1])} · ${x[2]}%</span></div>`).join(''):'<div class="empty-evidence">当前筛选范围暂无明确提及</div>';
async function loadCategoryData(category){if(filterData.categories[category.name])return;if(categoryLoads.has(category.name))return categoryLoads.get(category.name);const file=dataManifest?.categories?.[category.name];if(!file)throw new Error(`缺少${category.name}的数据文件映射`);const task=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=`data/${file}`;script.async=true;script.onload=()=>{const payload=window.REVIEW_CATEGORY_DATA?.[category.name];script.remove();if(!payload){reject(new Error(`${category.name}数据内容无效`));return}filterData.categories[category.name]=payload;delete window.REVIEW_CATEGORY_DATA[category.name];resolve()};script.onerror=()=>{script.remove();reject(new Error(`${category.name}数据文件加载失败`))};document.head.appendChild(script)}).finally(()=>categoryLoads.delete(category.name));categoryLoads.set(category.name,task);return task}
function renderCategoryLoading(category){document.getElementById('categoryDetail').innerHTML=`<section class="card load-state" role="status"><div class="loader" aria-hidden="true"></div><h2>正在加载${esc(category.name)}评论数据</h2><p>仅在首次打开该类目时加载。</p></section>`}
function renderCategoryList(){document.getElementById('categoryList').innerHTML=categories.map((c,i)=>`<button type="button" class="cat-button" data-cat="${i}" aria-current="${i===selectedCategory?'true':'false'}"><span>${c.name}</span><small>${fmt(c.unique)}</small></button>`).join('');document.querySelectorAll('.cat-button').forEach(b=>b.addEventListener('click',async()=>{selectedCategory=Number(b.dataset.cat);selectedShop='全部店铺';selectedTheme=0;renderCategoryList();const category=categories[selectedCategory];renderCategoryLoading(category);try{await loadCategoryData(category);renderCategoryDetail()}catch(error){renderLoadError(error.message)}}))}
function renderThemeEvidence(c,segment){const theme=c.themes[selectedTheme]?.[0]||c.themes[0][0],detail=segment?.themes?.[theme],container=document.getElementById('themeEvidence');if(!container)return;document.querySelectorAll('.theme-tab').forEach(button=>button.setAttribute('aria-current',button.dataset.theme===theme?'true':'false'));if(!detail){container.innerHTML='<div class="empty-evidence">当前筛选范围没有可用主题证据。</div>';return}const quotes=detail.quotes.length?`<div class="quote-grid">${detail.quotes.map((q,i)=>`<blockquote class="quote-card"><p>“${esc(q.text)}”</p><footer>代表评论 ${i+1} · ${esc(q.shop)} · ${esc(q.month)}</footer></blockquote>`).join('')}</div>`:'<div class="empty-evidence">该主题在当前筛选范围样本较少，暂不展示代表评论。</div>';container.innerHTML=`<div class="theme-evidence-head"><div><h2>${esc(theme)}｜评论内容延伸</h2><p class="section-sub">点击上方主题标注切换；代表评论来自当前时间与店铺筛选范围，并做精确文本去重。</p></div><div class="theme-stat"><b>${detail.rate}%</b><span class="small">${fmt(detail.count)}条主题评论</span></div></div><div class="theme-summary">${esc(detail.summary)}</div>${quotes}`}
function bindFilters(c,displayC,signalData,bRows){const time=document.getElementById('timeSelect'),shop=document.getElementById('shopSelect');time.addEventListener('change',()=>{selectedMonth=time.value;selectedShop='全部店铺';selectedTheme=0;renderCategoryDetail()});shop.addEventListener('change',()=>{selectedShop=shop.value;selectedTheme=0;renderCategoryDetail()});document.querySelectorAll('.theme-tab').forEach(button=>button.addEventListener('click',()=>{selectedTheme=displayC.themes.findIndex(t=>t[0]===button.dataset.theme);renderThemeEvidence(c,getSegment(c))}));renderThemeEvidence(c,getSegment(c));requestAnimationFrame(()=>drawCategoryCharts(displayC,signalData,bRows))}
function renderCategoryDetail(){const c=categories[selectedCategory],data=getCategoryFilter(c),shops=availableShops(c);if(selectedShop!=='全部店铺'&&!shops.includes(selectedShop))selectedShop='全部店铺';const segment=getSegment(c),smallSample=!segment||segment.n<30,displayC=displayCategory(c),bRows=brandRows(c),eligible=bRows.filter(x=>x.n>=30),best=eligible[0],lowRisk=eligible.slice().sort((a,b)=>a.riskRate-b.riskRate||b.n-a.n)[0],selectedRank=selectedShop==='全部店铺'?0:eligible.findIndex(x=>x.shop===selectedShop)+1,signalData={purposes:segment?.purposes?.length?segment.purposes:[['暂无明确目的',0,0]],keywords:segment?.keywords?.length?segment.keywords:[['暂无明确关键词',0,0]]},timeOptions=['全部时间',...filterData.months.slice().reverse()].map(v=>`<option value="${esc(v)}" ${v===selectedMonth?'selected':''}>${esc(v)}</option>`).join(''),shopOptions=['全部店铺',...shops].map(v=>`<option value="${esc(v)}" ${v===selectedShop?'selected':''}>${esc(v)}</option>`).join(''),posTerms=segment?.positiveTerms||[],negTerms=segment?.negativeTerms||[],co=segment?.co||[];document.getElementById('categoryDetail').innerHTML=`
  <div class="card filter-toolbar"><div class="filter-field"><label for="timeSelect">评论时间（年/月）</label><select id="timeSelect">${timeOptions}</select></div><div class="filter-field"><label for="shopSelect">子品牌 / 店铺</label><select id="shopSelect">${shopOptions}</select></div><div class="store-score ${smallSample?'sample-muted':''}"><div class="score-main"><b>${smallSample?'—':segment.score+' / 5'}</b><span>${selectedShop==='全部店铺'?'类目综合':'店铺'}文本体验分</span></div><div class="score-metric"><b>${fmt(segment?.n||0)}</b><span>去重评论</span></div><div class="score-metric"><b>${smallSample?'—':segment.positiveRate+'%'}</b><span>正向表达率</span></div><div class="score-metric"><b>${smallSample?'—':segment.riskRate+'%'}</b><span>风险提及率</span></div>${smallSample?'<div class="sample-warning">样本少于30条：仅展示评论内容，不计算体验分、不参与品牌排名。</div>':`<div class="score-caveat">${segment.confidence}证据 · 文本体验分仅用于同口径趋势观察，不是平台店铺星级。</div>`}</div></div>
  <div class="card category-hero-card"><div class="cat-hero"><div><h2>${c.name}</h2><div class="small">${esc(selectedMonth)} · ${esc(selectedShop)} · ${fmt(segment?.n||0)}条精确去重评论</div></div><div class="cat-score ${smallSample?'sample-muted':''}"><span class="small">风险内容信号</span><b>${smallSample?'—':segment.riskRate+'%'}</b><span class="small">${smallSample?'样本不足':'非星级差评率'}</span></div></div>
  <div class="insight-grid"><div class="insight-box purpose-card"><h3><span class="icon">◎</span>购买任务</h3><p>${esc(labels(segment?.purposes))}</p></div><div class="insight-box strength-card"><h3><span class="icon">✓</span>认可表达</h3><p>${esc(labels(posTerms))}</p></div><div class="insight-box scene-card"><h3><span class="icon">⌖</span>场景与人群</h3><p>${esc(labels([...(segment?.scenes||[]),...(segment?.people||[])].slice(0,4)))}</p></div></div></div>
  <div class="visual-grid"><section class="chart-stage"><h2><span class="icon">◇</span>类目主题画像</h2><p>按当前筛选联动；点击标注下钻评论证据</p><canvas id="themeRadar" role="img" aria-label="${c.name}主题雷达图，固定刻度0到50%">${c.name}主题提及率：${displayC.themes.map(t=>t[0]+' '+t[2]+'%').join('；')}</canvas><div class="theme-tabs">${displayC.themes.map((t,i)=>`<button type="button" class="theme-tab" data-theme="${esc(t[0])}" aria-current="${i===selectedTheme?'true':'false'}">${esc(t[0])} · ${t[2]}%</button>`).join('')}</div><div class="sr-only">${displayC.themes.map(t=>t[0]+'：'+t[2]+'%').join('；')}</div></section><section class="purpose-stage"><h2><span class="icon">◎</span>购买目的提及率</h2><p>当前筛选去重评论，多目的可同时命中</p><canvas id="purposeBars" role="img" aria-label="${c.name}购买目的提及率图">${signalData.purposes.map(v=>v[0]+' '+v[2]+'%').join('；')}</canvas><div class="sr-only">${signalData.purposes.map(v=>v[0]+'：'+v[2]+'%').join('；')}</div></section><section class="brand-stage"><h2><span class="icon">★</span>品牌评分对比</h2><p>${esc(selectedMonth)} · 仅比较不少于30条去重评论的店铺</p><canvas id="brandBars" role="img" aria-label="${c.name}店铺文本体验分对比">${eligible.map(v=>v.shop+' '+v.score+'分').join('；')}</canvas><div class="sr-only">${eligible.map(v=>v.shop+'：'+v.score+'分，'+v.n+'条').join('；')}</div></section></div>
  <section class="card theme-evidence" id="themeEvidence" aria-live="polite"></section>
  <div class="card signal-section"><h2 class="section-title"><span class="icon">⌁</span>人群 · 场景 · 目的</h2><p class="section-sub">全部按当前导航筛选更新；百分比以当前${fmt(segment?.n||0)}条去重评论为分母</p><div class="signal-grid"><div class="signal-panel"><h3>👤 明确人群</h3>${signalRows(segment?.people)}</div><div class="signal-panel"><h3>⌖ 使用场景</h3>${signalRows(segment?.scenes)}</div><div class="signal-panel"><h3>◎ 购买目的</h3>${signalRows(segment?.purposes)}</div></div></div>
  <section class="keyword-story"><div class="keyword-chart-wrap"><h2><span class="icon">#</span>关键词影响力</h2><p>当前筛选去重评论提及率 Top 8</p><canvas id="keywordBars" role="img" aria-label="${c.name}关键词横向条形图">${signalData.keywords.map(v=>v[0]+' '+v[2]+'%').join('；')}</canvas></div><div class="keyword-copy"><h2>价值判断词</h2><p>点击导航后同步更新，不把关键词直接等同于情感结论</p><div class="keyword-cloud">${signalData.keywords.map(k=>`<span class="keyword-pill">${esc(k[0])}<small>${fmt(k[1])} · ${k[2]}%</small></span>`).join('')}</div></div></section>
  <div class="analysis-triad"><div class="card co-card"><h2 class="section-title"><span class="icon">↔</span>问题共现</h2><p class="section-sub">同一条评论同时命中两个主题</p>${co.length?co.map(x=>`<div class="signal-row"><span><b>${esc(x[0])}</b></span><span>${fmt(x[1])}条 · ${x[2]}%</span></div>`).join(''):'<div class="empty-evidence">当前筛选暂无明显共现链路</div>'}</div>
  <div class="card evolution-card"><h2 class="section-title"><span class="icon">→</span>内容演化</h2><p class="section-sub">从期待、验证到风险触发</p><div class="finding"><b>期待</b><span class="small">${esc(labels(segment?.purposes))}</span></div><div class="finding"><b>验证</b><span class="small">围绕${esc(labels(segment?.keywords))}判断价值</span></div><div class="finding"><b>风险</b><span class="small">${esc(labels(negTerms))}</span></div></div>
  <div class="card pain-card"><h2 class="section-title"><span class="icon">!</span>核心痛点</h2><p class="section-sub">当前筛选中的风险表达词，不代表因果</p>${negTerms.length?negTerms.map((x,i)=>`<div class="finding"><b>${i+1}. ${esc(x[0])}</b><span class="small">${fmt(x[1])}条评论出现</span></div>`).join(''):'<div class="empty-evidence">当前筛选未形成集中风险词</div>'}</div></div>
  <div class="card brand-insight"><h2 class="section-title"><span class="icon">★</span>品牌之间对比分析</h2><p class="section-sub">同类目、同月份、同一文本推断口径；少于30条的店铺不参与排名</p><div class="brand-compare-grid"><div class="brand-compare-card"><b>体验领先</b><span>${best?`${esc(best.shop)} · ${best.score}/5 · ${fmt(best.n)}条`:'可比样本不足'}</span></div><div class="brand-compare-card"><b>风险控制</b><span>${lowRisk?`${esc(lowRisk.shop)} · 风险${lowRisk.riskRate}%`:'可比样本不足'}</span></div><div class="brand-compare-card"><b>${selectedShop==='全部店铺'?'可比范围':'当前品牌位置'}</b><span>${selectedShop==='全部店铺'?`${eligible.length}家店铺达到比较门槛`:selectedRank?`第${selectedRank}/${eligible.length} · ${segment.score}/5`:'样本不足，不参与排名'}</span></div></div><div class="compare-grid" style="margin-top:12px"><div class="compare-box"><h3>✓ 正向表达集中</h3><p>${esc(labels(posTerms))}</p></div><div class="compare-box highlight"><h3>! 主要风险差异</h3><p>${esc(labels(negTerms))}</p></div></div></div>
  `;bindFilters(c,displayC,signalData,bRows)}
function prepCanvas(id){const el=document.getElementById(id);if(!el)return null;const dpr=Math.min(window.devicePixelRatio||1,2),r=el.getBoundingClientRect();el.width=Math.max(1,Math.round(r.width*dpr));el.height=Math.max(1,Math.round(r.height*dpr));const x=el.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);return{el,x,w:r.width,h:r.height}}
function drawCategoryCharts(c,s,bRows){drawRadar(c);drawPurposes(s);drawBrands(bRows);drawKeywords(s)}
function drawRadar(c){const o=prepCanvas('themeRadar');if(!o)return;const{x,w,h}=o,cx=w/2,cy=h/2+8,R=Math.min(w*.30,h*.36),n=c.themes.length,max=50;x.clearRect(0,0,w,h);x.lineWidth=1;for(let ring=1;ring<=4;ring++){x.beginPath();for(let i=0;i<n;i++){const a=-Math.PI/2+i*Math.PI*2/n,r=R*ring/4,px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r;i?x.lineTo(px,py):x.moveTo(px,py)}x.closePath();x.strokeStyle='rgba(255,255,255,.18)';x.stroke()}for(let i=0;i<n;i++){const a=-Math.PI/2+i*Math.PI*2/n;x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);x.strokeStyle='rgba(255,255,255,.16)';x.stroke();const lx=cx+Math.cos(a)*(R+24),ly=cy+Math.sin(a)*(R+18);x.fillStyle='rgba(255,255,255,.86)';x.font='12px system-ui';x.textAlign=Math.cos(a)>.25?'left':Math.cos(a)<-.25?'right':'center';x.textBaseline=Math.sin(a)>.4?'top':Math.sin(a)<-.4?'bottom':'middle';x.fillText(c.themes[i][0],lx,ly)}x.beginPath();c.themes.forEach((v,i)=>{const a=-Math.PI/2+i*Math.PI*2/n,r=R*Math.min(v[2],max)/max,px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r;i?x.lineTo(px,py):x.moveTo(px,py)});x.closePath();const g=x.createLinearGradient(cx-R,cy-R,cx+R,cy+R);g.addColorStop(0,'rgba(61,178,255,.72)');g.addColorStop(1,'rgba(139,92,246,.58)');x.fillStyle=g;x.fill();x.strokeStyle='#8fd4ff';x.lineWidth=2;x.stroke();c.themes.forEach((v,i)=>{const a=-Math.PI/2+i*Math.PI*2/n,r=R*Math.min(v[2],max)/max,px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r;x.beginPath();x.arc(px,py,4,0,Math.PI*2);x.fillStyle='#fff';x.fill();x.fillStyle='#fff';x.font='600 11px system-ui';x.textAlign='center';x.fillText(v[2]+'%',px,py-9)})}
function drawPurposes(s){const o=prepCanvas('purposeBars');if(!o)return;const{x,w,h}=o,data=s.purposes.slice(0,6),max=50,left=92,right=42,top=12,row=(h-24)/data.length,colors=['#3478f6','#12a67a','#f59e0b','#8b5cf6','#ef5b5b','#27ae60'];x.clearRect(0,0,w,h);data.forEach((v,i)=>{const y=top+i*row+row*.22,bw=(w-left-right)*Math.min(v[2],max)/max;x.fillStyle='rgba(120,110,160,.12)';x.fillRect(left,y,w-left-right,row*.42);x.fillStyle=colors[i];x.fillRect(left,y,bw,row*.42);x.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--ink').trim()||'#17202a';x.font='12px system-ui';x.textAlign='right';x.textBaseline='middle';x.fillText(v[0],left-8,y+row*.21);x.textAlign='left';x.fillText(v[2]+'%',Math.min(left+bw+6,w-right+3),y+row*.21)})}
function drawBrands(rows){const o=prepCanvas('brandBars');if(!o)return;const{x,w,h}=o,data=rows.filter(v=>v.n>=30).slice(0,7),left=Math.min(116,w*.42),right=38,top=8,row=(h-16)/Math.max(data.length,1);x.clearRect(0,0,w,h);if(!data.length){x.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--muted').trim()||'#667085';x.font='13px system-ui';x.textAlign='center';x.fillText('当前月份可比样本不足',w/2,h/2);return}data.forEach((v,i)=>{const y=top+i*row+row*.22,bw=(w-left-right)*v.score/5,active=v.shop===selectedShop;x.fillStyle='rgba(14,147,132,.12)';x.fillRect(left,y,w-left-right,row*.44);const g=x.createLinearGradient(left,0,left+bw,0);g.addColorStop(0,active?'#6941c6':'#0e9384');g.addColorStop(1,active?'#9b7cff':'#36c6a8');x.fillStyle=g;x.fillRect(left,y,bw,row*.44);x.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--ink').trim()||'#17202a';x.font=active?'700 11px system-ui':'11px system-ui';x.textAlign='right';x.textBaseline='middle';const name=v.shop.length>9?v.shop.slice(0,8)+'…':v.shop;x.fillText(name,left-7,y+row*.22);x.textAlign='left';x.fillText(v.score.toFixed(1),Math.min(left+bw+5,w-right+3),y+row*.22)})}
function drawKeywords(s){const o=prepCanvas('keywordBars');if(!o)return;const{x,w,h}=o,data=s.keywords.slice(0,8),max=Math.max(1,...data.map(v=>v[2])),left=70,right=46,top=10,row=(h-20)/data.length,colors=['#3478f6','#12a67a','#f59e0b','#8b5cf6'];x.clearRect(0,0,w,h);data.forEach((v,i)=>{const y=top+i*row+row*.22,bw=(w-left-right)*v[2]/max;x.fillStyle='rgba(130,145,165,.13)';x.fillRect(left,y,w-left-right,row*.46);const g=x.createLinearGradient(left,0,left+bw,0);g.addColorStop(0,colors[i%4]);g.addColorStop(1,colors[(i+1)%4]);x.fillStyle=g;x.fillRect(left,y,bw,row*.46);x.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--ink').trim()||'#17202a';x.font='12px system-ui';x.textAlign='right';x.textBaseline='middle';x.fillText(v[0],left-9,y+row*.23);x.textAlign='left';x.fillText(v[2]+'%',Math.min(left+bw+6,w-right+4),y+row*.23)})}
function currentChartData(){const c=categories[selectedCategory],segment=getSegment(c);return{c,displayC:displayCategory(c),signals:{purposes:segment?.purposes?.length?segment.purposes:[['暂无明确目的',0,0]],keywords:segment?.keywords?.length?segment.keywords:[['暂无明确关键词',0,0]]},brands:brandRows(c)}}
let resizeTimer;window.addEventListener('resize',()=>{const c=categories[selectedCategory];if(!filterData.categories[c.name])return;clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{const d=currentChartData();drawCategoryCharts(d.displayC,d.signals,d.brands)},220)});
function renderLoadError(message='请检查网络连接后重试。'){document.getElementById('categoryDetail').innerHTML=`<section class="card load-state error-state" role="alert"><div class="error-icon" aria-hidden="true">!</div><h2>评论分析数据加载失败</h2><p>${esc(message)} 页面不会把加载失败显示为零值。</p><button type="button" class="retry-button" id="retryData">重新加载</button></section>`;document.getElementById('retryData').addEventListener('click',()=>location.reload())}
async function start(){try{if(window.__VOC_MANIFEST_ERROR__||!window.REVIEW_MANIFEST?.categories)throw new Error('数据清单加载失败');dataManifest=window.REVIEW_MANIFEST;filterData.months=dataManifest.months||[];renderCategoryList();renderCategoryLoading(categories[0]);await loadCategoryData(categories[0]);renderCategoryDetail()}catch(error){renderLoadError(error.message)}document.getElementById('themeBtn').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';document.getElementById('themeBtn').textContent=dark?'深色模式':'浅色模式';const c=categories[selectedCategory];if(filterData.categories[c.name])requestAnimationFrame(()=>{const d=currentChartData();drawCategoryCharts(d.displayC,d.signals,d.brands)})})}
start();
})();
