(()=>{
'use strict';
const categories=window.REVIEW_INSIGHTS||[],manifest=window.REVIEW_MANIFEST,payloads={},colors=['#1877f2','#8b5cf6','#18a77b','#f59e0b','#ef5b5b','#25a4c4','#d946ef','#64748b','#84cc16','#f97316','#0ea5e9','#a855f7'];
const saved=(()=>{try{return JSON.parse(localStorage.getItem('vocDateRange')||'{}')}catch{return {}}})();
const valid=value=>value&&value>=manifest?.minDate&&value<=manifest?.maxDate?value:null;
const state={start:valid(saved.start)||manifest?.minDate||'',end:valid(saved.end)||manifest?.maxDate||'',metric:'share',selected:new Set(),auto:true};
if(state.start>state.end)[state.start,state.end]=[state.end,state.start];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('zh-CN');
const pct=v=>v==null?'—':`${v>=0?'+':''}${v.toFixed(1)}%`;
const date=value=>new Date(`${value}T00:00:00Z`);
const iso=d=>d.toISOString().slice(0,10);
const addDays=(value,n)=>{const d=typeof value==='string'?date(value):new Date(value);d.setUTCDate(d.getUTCDate()+n);return iso(d)};
const diffDays=(a,b)=>Math.round((date(b)-date(a))/86400000);
const monday=value=>{const d=date(value),day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()-day+1);return iso(d)};
const monthStart=value=>`${value.slice(0,7)}-01`;
const addMonth=value=>{const d=date(value);d.setUTCMonth(d.getUTCMonth()+1);return iso(d)};
const inRange=r=>r.date>=state.start&&r.date<=state.end;
const allRows=name=>payloads[name]?.ratings||[];
const rangeRows=name=>allRows(name).filter(inRange);
const fullRange=()=>state.start===manifest.minDate&&state.end===manifest.maxDate;
function loadCategory(c){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=`data/${manifest.categories[c.name]}?v=20260820-2`;s.onload=()=>{const p=window.REVIEW_CATEGORY_DATA?.[c.name];s.remove();if(!p)return reject(new Error(`${c.name}数据无效`));payloads[c.name]=p;delete window.REVIEW_CATEGORY_DATA[c.name];resolve()};s.onerror=()=>{s.remove();reject(new Error(`${c.name}数据加载失败`))};document.head.appendChild(s)})}
async function loadAll(){await Promise.all(categories.map(loadCategory))}
function saveRange(){localStorage.setItem('vocDateRange',JSON.stringify({start:state.start,end:state.end}))}
function setDates(start,end){state.start=start;state.end=end;if(state.start>state.end)[state.start,state.end]=[state.end,state.start];state.auto=true;saveRange();render()}
function categoryCounts(){return categories.map((c,i)=>({name:c.name,index:i,count:rangeRows(c.name).length})).sort((a,b)=>b.count-a.count||a.index-b.index)}
function ensureSelection(stats){const available=new Set(stats.filter(x=>x.count).map(x=>x.name));state.selected=new Set([...state.selected].filter(x=>available.has(x)));if(state.auto){state.selected=new Set(stats.slice(0,5).map(x=>x.name));state.auto=false}}
function sidebar(stats){ensureSelection(stats);document.getElementById('attentionSidebar').innerHTML=`<nav class="page-switch" aria-label="看板页面"><a href="dashboard-v3.html">VOC洞察</a><a href="rating-dashboard.html">店铺好评</a><a class="active" href="attention-dashboard.html">品类关注</a></nav><div class="sidebar-label important">1. 时间范围</div><div class="side-filter"><div class="date-range"><span><small>开始日期</small><input type="date" id="startDate" min="${manifest.minDate}" max="${manifest.maxDate}" value="${state.start}"></span><i>至</i><span><small>结束日期</small><input type="date" id="endDate" min="${manifest.minDate}" max="${manifest.maxDate}" value="${state.end}"></span></div><div class="date-presets"><button data-days="all" class="${fullRange()?'active':''}">全部</button><button data-days="28">近4周</button><button data-days="84">近12周</button><button data-days="ytd">今年</button></div></div><div class="sidebar-label important">2. 对比品类</div><div class="store-tools"><button id="topCategories">前5品类</button><button id="clearCategories">清空</button></div><div class="category-checks">${stats.map(s=>`<label><input type="checkbox" value="${esc(s.name)}" ${state.selected.has(s.name)?'checked':''}><i style="--store-color:${colors[s.index%colors.length]}"></i><span>${esc(s.name)}</span><small>${fmt(s.count)}条</small></label>`).join('')}</div>`;
  document.getElementById('startDate').onchange=e=>setDates(e.target.value,state.end);document.getElementById('endDate').onchange=e=>setDates(state.start,e.target.value);
  document.querySelectorAll('.date-presets button').forEach(b=>b.onclick=()=>{const v=b.dataset.days,end=date(manifest.maxDate);if(v==='all')return setDates(manifest.minDate,manifest.maxDate);if(v==='ytd')return setDates(`${end.getUTCFullYear()}-01-01`,manifest.maxDate);return setDates(addDays(manifest.maxDate,-Number(v)+1),manifest.maxDate)});
  document.querySelectorAll('.category-checks input').forEach(input=>input.onchange=()=>{input.checked?state.selected.add(input.value):state.selected.delete(input.value);state.auto=false;render()});
  document.getElementById('topCategories').onclick=()=>{state.selected=new Set(stats.slice(0,5).map(x=>x.name));state.auto=false;render()};document.getElementById('clearCategories').onclick=()=>{state.selected.clear();state.auto=false;render()};
}
function buildSeries(){const grain=diffDays(state.start,state.end)<=196?'week':'month',periods=[],first=grain==='week'?monday(state.start):monthStart(state.start);for(let key=first;key<=state.end;key=grain==='week'?addDays(key,7):addMonth(key)){const end=grain==='week'?addDays(key,6):addDays(addMonth(key),-1);periods.push({key,end,label:grain==='week'?`${Number(key.slice(5,7))}/${Number(key.slice(8,10))}`:`${key.slice(0,4)}/${Number(key.slice(5,7))}`})}const counts=new Map(categories.map(c=>[c.name,periods.map(()=>0)]));categories.forEach(c=>rangeRows(c.name).forEach(r=>{const key=grain==='week'?monday(r.date):monthStart(r.date),i=periods.findIndex(p=>p.key===key);if(i>=0)counts.get(c.name)[i]++}));const totals=periods.map((_,i)=>categories.reduce((sum,c)=>sum+counts.get(c.name)[i],0)),values=new Map();categories.forEach(c=>{const arr=counts.get(c.name);values.set(c.name,arr.map((count,i)=>{if(state.metric==='volume')return count;if(state.metric==='share')return totals[i]?count*100/totals[i]:null;if(i<4)return null;const avg=arr.slice(i-4,i).reduce((a,b)=>a+b,0)/4;return avg?count*100/avg:null}))});return {grain,periods,counts,totals,values}}
function lastCompleteSunday(){const d=date(state.end),day=d.getUTCDay();if(day)d.setUTCDate(d.getUTCDate()-day);return iso(d)}
function comparison(){const curEnd=lastCompleteSunday(),curStart=addDays(curEnd,-27),prevEnd=addDays(curStart,-1),prevStart=addDays(prevEnd,-27),available=state.start<=prevStart,items=categories.map((c,i)=>{const rows=allRows(c.name),cur=rows.filter(r=>r.date>=curStart&&r.date<=curEnd).length,prev=rows.filter(r=>r.date>=prevStart&&r.date<=prevEnd).length,last=rows.filter(r=>r.date<=state.end).map(r=>r.date).sort().at(-1)||null,gap=last?diffDays(last,state.end):999,status=gap<=7?'current':gap<=14?'delayed':'stale',change=prev?((cur-prev)/prev*100):null;return {name:c.name,index:i,cur,prev,change,last,gap,status}}),curTotal=items.reduce((a,x)=>a+x.cur,0),prevTotal=items.reduce((a,x)=>a+x.prev,0);items.forEach(x=>x.share=curTotal?x.cur*100/curTotal:0);return {available,curStart,curEnd,prevStart,prevEnd,items,curTotal,prevTotal,delta:prevTotal?(curTotal-prevTotal)*100/prevTotal:null}}
function kpis(cmp){const valid=cmp.available?cmp.items.filter(x=>x.status!=='stale'&&x.cur+x.prev>=30&&x.change!=null):[],rising=valid.filter(x=>x.change>5).length,current=cmp.items.filter(x=>x.status==='current').length,top=cmp.items.slice().sort((a,b)=>b.cur-a.cur)[0];const cards=[['最近4完整周',fmt(cmp.curTotal),`${cmp.curStart} 至 ${cmp.curEnd}`],['较前4周',cmp.available?pct(cmp.delta):'—',cmp.available?`${fmt(cmp.prevTotal)}条基期`:'所选范围不足8周'],['上升品类',cmp.available?fmt(rising):'—','增幅>5%且数据连续'],['正常更新',`${current} / ${categories.length}`,'距结束日期≤7天'],['关注份额最高',top?top.name:'—',top?`${top.share.toFixed(1)}% · ${fmt(top.cur)}条`:'暂无数据']];return `<section class="attention-kpis">${cards.map((x,i)=>`<div class="card attention-kpi kpi-${i}"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}</section>`}
function metricLabel(){return state.metric==='volume'?'评论量':state.metric==='share'?'关注份额':'关注指数'}
function chartCard(series,stats){const selected=stats.filter(x=>state.selected.has(x.name)),grain=series.grain==='week'?'周':'月';return `<section class="card attention-chart"><div class="section-head chart-title"><div><h2>品类${grain}度关注趋势</h2><p>${state.metric==='volume'?'原始评论新增量':state.metric==='share'?'品类评论量占同期全品类评论量':'当前周期相对前4周期平均值，100为持平'}</p></div><div class="metric-tabs">${[['share','关注份额'],['volume','评论量'],['index','关注指数']].map(x=>`<button data-attention-metric="${x[0]}" class="${state.metric===x[0]?'active':''}">${x[1]}</button>`).join('')}</div></div><div class="chart-legend attention-legend">${selected.map(s=>`<span><i style="--store-color:${colors[s.index%colors.length]}"></i>${esc(s.name)}<small>${fmt(s.count)}条</small></span>`).join('')||'<em>请在左侧选择品类</em>'}</div><div class="attention-canvas-wrap"><canvas id="attentionChart" role="img" aria-label="品类${metricLabel()}趋势"></canvas></div><div class="chart-footnote"><b>口径提醒：</b>长日期范围自动按月聚合，26周以内按周聚合；评论关注度代表当前数据源中的反馈活跃度，不等同于搜索热度或市场规模。</div></section>`}
function chartScale(series){const vals=[];series.values.forEach((arr,name)=>{if(state.selected.has(name))arr.forEach(v=>{if(v!=null)vals.push(v)})});const high=Math.max(1,...vals);if(state.metric==='volume')return {max:Math.max(10,Math.ceil(high/100)*100),suffix:''};if(state.metric==='share')return {max:Math.max(10,Math.ceil(high/5)*5),suffix:'%'};return {max:Math.max(150,Math.ceil(high/50)*50),suffix:''}}
function drawChart(series,stats){const el=document.getElementById('attentionChart');if(!el)return;const rect=el.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=rect.width,h=rect.height;el.width=Math.round(w*dpr);el.height=Math.round(h*dpr);const x=el.getContext('2d');x.scale(dpr,dpr);const css=getComputedStyle(document.documentElement),muted=css.getPropertyValue('--muted').trim(),line=css.getPropertyValue('--line').trim(),scale=chartScale(series),pad={l:52,r:18,t:18,b:48},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,n=Math.max(1,series.periods.length-1),toY=v=>pad.t+ch*(1-v/scale.max);x.clearRect(0,0,w,h);x.font='10px system-ui';x.textBaseline='middle';for(let i=0;i<=4;i++){const value=scale.max*i/4,y=toY(value);x.strokeStyle=line;x.lineWidth=1;x.setLineDash([]);x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.fillStyle=muted;x.textAlign='right';x.fillText(`${Number.isInteger(value)?value:value.toFixed(1)}${scale.suffix}`,pad.l-7,y)}if(state.metric==='index'&&scale.max>=100){const y=toY(100);x.setLineDash([5,4]);x.strokeStyle='#f59e0b';x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.setLineDash([])}const step=Math.max(1,Math.ceil(series.periods.length/8));series.periods.forEach((p,i)=>{if(i%step&&i!==series.periods.length-1)return;const px=pad.l+cw*i/n;x.fillStyle=muted;x.textAlign='center';x.fillText(p.label,px,h-pad.b+18)});stats.filter(s=>state.selected.has(s.name)).forEach(s=>{const arr=series.values.get(s.name),color=colors[s.index%colors.length];let previous=null;arr.forEach((v,i)=>{if(v==null){previous=null;return}const px=pad.l+cw*i/n,py=toY(v);if(previous){const bend=(px-previous.x)*.42;x.strokeStyle=color;x.lineWidth=2.3;x.beginPath();x.moveTo(previous.x,previous.y);x.bezierCurveTo(previous.x+bend,previous.y,px-bend,py,px,py);x.stroke()}x.fillStyle=color;x.beginPath();x.arc(px,py,3,0,Math.PI*2);x.fill();previous={x:px,y:py}})})}
function heatmap(cmp){const end=cmp.curEnd,weeks=[];for(let i=11;i>=0;i--){const start=addDays(addDays(end,-6),-7*i);if(addDays(start,6)>=state.start)weeks.push({start,end:addDays(start,6),label:`${Number(start.slice(5,7))}/${Number(start.slice(8,10))}`})}const rows=cmp.items.map(item=>{const counts=weeks.map(w=>allRows(item.name).filter(r=>r.date>=w.start&&r.date<=w.end).length),max=Math.max(1,...counts);return `<div class="heat-row"><b>${esc(item.name)}</b>${counts.map((n,i)=>`<span style="--heat:${n/max}" title="${esc(item.name)} · ${weeks[i].start} 至 ${weeks[i].end} · ${n}条">${n}</span>`).join('')}</div>`}).join('');return `<section class="card attention-heat"><div class="section-head"><div><h2>近12周关注热力图</h2><p>每行颜色相对该品类自身12周最高值，数字为原始评论量</p></div></div><div class="heat-scroll" style="--heat-weeks:${Math.max(1,weeks.length)}"><div class="heat-head"><b>品类</b>${weeks.map(w=>`<span>${w.label}</span>`).join('')}</div>${rows}</div></section>`}
function movers(cmp){const valid=cmp.available?cmp.items.filter(x=>x.status!=='stale'&&x.cur+x.prev>=30&&x.change!=null):[],up=valid.filter(x=>x.change>5).sort((a,b)=>b.change-a.change).slice(0,4),down=valid.filter(x=>x.change<-5).sort((a,b)=>a.change-b.change).slice(0,4);const list=(title,items,tone)=>`<div class="mover-group ${tone}"><h3>${title}</h3>${items.map((x,i)=>`<div><span>${i+1}</span><b>${esc(x.name)}</b><strong>${pct(x.change)}</strong><small>${fmt(x.cur)}条</small></div>`).join('')||'<p>暂无超过5%的有效变化</p>'}</div>`;return `<section class="card movers-card"><div class="section-head"><div><h2>近4周升降榜</h2><p>对比前4个完整周，仅纳入数据连续且两期合计≥30条的品类</p></div></div>${list('上升最快',up,'up')}${list('下降最快',down,'down')}</section>`}
function statusTable(cmp){const label={current:'正常更新',delayed:'更新滞后',stale:'可能停止'},rows=cmp.items.slice().sort((a,b)=>b.cur-a.cur).map(x=>`<tr><td><i style="--store-color:${colors[x.index%colors.length]}"></i><b>${esc(x.name)}</b></td><td>${fmt(x.cur)}</td><td>${cmp.available?fmt(x.prev):'—'}</td><td class="${x.change==null?'':x.change>=0?'positive-change':'negative-change'}">${cmp.available?pct(x.change):'—'}</td><td>${x.share.toFixed(1)}%</td><td>${x.last||'—'}</td><td><span class="freshness ${x.status}">${label[x.status]}</span></td></tr>`).join('');return `<section class="card attention-table-card"><div class="section-head"><div><h2>品类关注与数据连续性</h2><p>下降结论必须结合最后更新日期判断</p></div><span>${cmp.curStart} 至 ${cmp.curEnd}</span></div><div class="table-scroll"><table class="rating-table attention-table"><thead><tr><th>品类</th><th>近4周</th><th>前4周</th><th>变化</th><th>关注份额</th><th>最后数据</th><th>状态</th></tr></thead><tbody>${rows}</tbody></table></div></section>`}
function render(){const stats=categoryCounts();sidebar(stats);const series=buildSeries(),cmp=comparison();document.getElementById('attentionDetail').innerHTML=`<section class="card attention-hero"><div><span>跨品类评论反馈活跃度</span><h1>品类关注趋势</h1><p>${state.start} 至 ${state.end} · ${series.grain==='week'?'按周':'按月'}展示</p></div><div><b>当前口径</b><strong>${metricLabel()}</strong><small>原始评论行 · 非搜索量/销量</small></div></section>${kpis(cmp)}${chartCard(series,stats)}<div class="attention-lower">${heatmap(cmp)}${movers(cmp)}</div>${statusTable(cmp)}<section class="card attention-method"><b>如何解读</b><p>评论量上升说明当前数据源中的购买后反馈更活跃；关注份额上升说明该品类在同期评论中的占比提高。若最后更新日期明显滞后，应优先判断为数据中断，不能直接解释为市场降温。</p></section>`;document.querySelectorAll('[data-attention-metric]').forEach(b=>b.onclick=()=>{state.metric=b.dataset.attentionMetric;render()});requestAnimationFrame(()=>drawChart(series,stats))}
function failure(message){document.getElementById('attentionDetail').innerHTML=`<section class="card load-state error-state"><div class="error-icon">!</div><h2>跨品类数据加载失败</h2><p>${esc(message)}。页面不会把加载失败显示为零值。</p><button class="retry-button" onclick="location.reload()">重新加载</button></section>`}
async function start(){try{if(window.__VOC_MANIFEST_ERROR__||!manifest?.categories)throw new Error('数据清单加载失败');await loadAll();render()}catch(e){failure(e.message)}document.getElementById('themeBtn').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';document.getElementById('themeBtn').textContent=dark?'深色模式':'浅色模式';render()}}
start();
})();
