(() => {
  "use strict";
  const D=window.COMPLAINT_DATA;if(!D)return;
  const $=s=>document.querySelector(s),fmt=new Intl.NumberFormat("zh-CN",{maximumFractionDigits:1});
  const kpis=$("#complaintKpis"),body=$("#complaintDashboardBody"),scope=$("#complaintScope"),platformSelect=$("#complaintPlatform"),shopSelect=$("#complaintShop");
  const safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const pct=v=>Number.isFinite(v)?`${v>=0?"+":""}${v.toFixed(1)}%`:"—",pp=v=>Number.isFinite(v)?`${v>=0?"+":""}${v.toFixed(1)}pp`:"—",change=(a,b)=>b>0?(a/b-1)*100:NaN;
  const typeCount=(row,i)=>Number(row?.[2+i]||0),resultCount=row=>Number(row?.[2+D.types.length]||0),state={grain:"week",platform:"",shop:""};
  const records=(D.records||[]).map(r=>({date:r[0],product:r[1],type:r[2],tags:r[3]||[],result:+r[4]||0,status:+r[5]||0,platform:r[6]||"",shop:r[7]||""}));
  const detailRecords=records.length?records:(D.recentDetails||[]).map(r=>({date:r[0],product:r[1],type:r[2],tags:r[3]||[],result:+r[4]||0,status:+r[5]||0,platform:"",shop:""}));
  const channelCoverage=D.meta.recordCount?D.meta.storeExported/D.meta.recordCount*100:0,channelUsable=records.length>0&&channelCoverage>=90;
  function isoWeek(text){const d=new Date(`${text}T00:00:00Z`),day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const s=new Date(Date.UTC(d.getUTCFullYear(),0,1)),w=Math.ceil((((d-s)/86400000)+1)/7);return `${d.getUTCFullYear()}-W${String(w).padStart(2,"0")}`;}
  const periodOf=(r,g)=>g==="month"?r.date.slice(0,7):isoWeek(r.date),match=r=>(!state.platform||r.platform===state.platform)&&(!state.shop||r.shop===state.shop),scoped=()=>records.filter(match);
  function aggregate(period,grain=state.grain){if(!records.length)return(grain==="month"?D.months:D.weeks).find(r=>r[0]===period);const rows=scoped().filter(r=>periodOf(r,grain)===period),counts=D.types.map(t=>rows.filter(r=>r.type===t).length);return[period,rows.length,...counts,rows.reduce((s,r)=>s+r.result,0),rows.reduce((s,r)=>s+r.status,0)];}
  const week=p=>aggregate(p,"week"),latest=()=>week(D.meta.latestCompleteWeek),previous=()=>week(D.meta.priorCompleteWeek),recentKeys=()=>D.weeks.filter(r=>r[0]<=D.meta.latestCompleteWeek).slice(-4).map(r=>r[0]),recent=()=>recentKeys().map(week),average=rows=>rows.length?rows.reduce((s,r)=>s+Number(r?.[1]||0),0)/rows.length:NaN;
  function refreshFilters(){const platforms=[...new Set(records.map(r=>r.platform))].filter(Boolean).sort(),shops=[...new Set(records.filter(r=>!state.platform||r.platform===state.platform).map(r=>r.shop))].filter(Boolean).sort();if(!channelUsable){platformSelect.innerHTML='<option>关联平台权限待开放</option>';shopSelect.innerHTML='<option>关联店铺权限待开放</option>';platformSelect.disabled=shopSelect.disabled=true;state.platform=state.shop="";return;}platformSelect.disabled=shopSelect.disabled=false;platformSelect.innerHTML='<option value="">全部平台</option>'+platforms.map(v=>`<option value="${safe(v)}">${safe(v)}</option>`).join("");platformSelect.value=state.platform;if(state.shop&&!shops.includes(state.shop))state.shop="";shopSelect.innerHTML='<option value="">全部店铺</option>'+shops.map(v=>`<option value="${safe(v)}">${safe(v)}</option>`).join("");shopSelect.value=state.shop;}
  const card=(l,v,c,n,t="")=>`<article class="complaint-kpi ${t}"><span>${safe(l)}</span><strong>${safe(v)}</strong><b>${safe(c)}</b><small>${safe(n)}</small></article>`;
  function renderKpis(){const cur=latest(),pre=previous(),four=recent(),avg=average(four),ct=cur?.[1]||0,pt=pre?.[1]||0,cr=ct?resultCount(cur)/ct*100:NaN,pr=pt?resultCount(pre)/pt*100:NaN,keys=new Set(recentKeys()),rows=records.length?scoped().filter(r=>keys.has(isoWeek(r.date))):detailRecords,valid=records.length?rows.filter(r=>!["未填写产品","未规范产品"].includes(r.product)).length:D.recentProductWeekly.reduce((s,r)=>s+r[1],0),total=four.reduce((s,r)=>s+Number(r?.[1]||0),0),coverage=total?valid/total*100:NaN,all=records.length?scoped():null,cumulative=all?(all.length?all.filter(r=>!["未填写产品","未规范产品"].includes(r.product)).length/all.length*100:NaN):(D.meta.recordCount-D.meta.missingProduct-D.meta.unstandardizedProduct)/D.meta.recordCount*100;kpis.innerHTML=card(`${D.meta.latestCompleteWeek} 投诉量`,`${fmt.format(ct)} 起`,`环比 ${pct(change(ct,pt))}`,`上周 ${fmt.format(pt)} 起；周一至周日`)+card("较近4周均值",pct(change(ct,avg)),`本周 ${fmt.format(ct)} 起 / 均值 ${fmt.format(avg)} 起`,four.map(r=>r?.[1]||0).join(" → "),"trend")+card("处理结果填写率",Number.isFinite(cr)?`${cr.toFixed(1)}%`:"—",`较上周 ${pp(cr-pr)}`,`${resultCount(cur)}/${ct} 条已填写`,"result")+card("近4周产品填写率",Number.isFinite(coverage)?`${coverage.toFixed(1)}%`:"—",Number.isFinite(cumulative)?`较累计 ${pp(coverage-cumulative)}`:"累计基期缺失",Number.isFinite(cumulative)?`累计 ${cumulative.toFixed(1)}%；缺失不是零`:"当前筛选无记录","quality");}
  function trendChart(){const weekly=state.grain==="week",src=weekly?D.weeks.filter(r=>r[0]<=D.meta.currentPartialWeek).slice(-9):D.months.filter(r=>r[0].startsWith("2026-")),rows=src.map(r=>aggregate(r[0],state.grain)||[r[0],0]),max=Math.max(1,...rows.map(r=>r[1])),W=1000,H=350,L=56,R=34,T=44,B=58,iw=W-L-R,ih=H-T-B,bar=Math.min(64,iw/Math.max(1,rows.length)*.58);let svg=`<svg class="complaint-trend-svg" viewBox="0 0 ${W} ${H}">`;for(let i=0;i<4;i++){const y=T+i*ih/3;svg+=`<line x1="${L}" y1="${y}" x2="${W-R}" y2="${y}" stroke="var(--line)"/>`;}rows.forEach((r,i)=>{const x=L+(i+.5)*iw/rows.length,h=r[1]/max*ih,y=T+ih-h,partial=(weekly&&r[0]===D.meta.currentPartialWeek)||(!weekly&&r[0]===D.meta.sourceMax.slice(0,7)),delta=change(r[1],rows[i-1]?.[1]);svg+=`<g><rect x="${x-bar/2}" y="${y}" width="${bar}" height="${h}" rx="8" fill="${partial?'var(--orange)':'var(--blue)'}" opacity=".82"/><text x="${x}" y="${Math.max(18,y-9)}" text-anchor="middle" font-size="13" font-weight="800">${r[1]}</text><text x="${x}" y="${H-29}" text-anchor="middle" fill="var(--muted)" font-size="12">${safe(r[0].replace(/^2026-/,""))}</text><text x="${x}" y="${H-11}" text-anchor="middle" fill="${partial?'var(--orange)':'var(--muted)'}" font-size="10">${partial?'部分周期':(Number.isFinite(delta)?pct(delta):'基期缺失')}</text></g>`;});return`<article class="card"><div class="section-head"><div><span class="section-index">01 · 投诉量趋势</span><h2>${weekly?"最近完整周与当前周":"2026年月度趋势"}</h2><p class="subtitle">趋势数量随平台和店铺筛选同步；部分周期不作评价</p></div></div>${svg}</svg></article>`;}
  function typeTable(){const cur=latest(),pre=previous(),four=recent(),total=cur?.[1]||0,rows=D.types.map((name,i)=>({name,count:typeCount(cur,i),last:typeCount(pre,i),trend:four.map(r=>typeCount(r,i))})).sort((a,b)=>b.count-a.count),max=Math.max(1,...rows.map(r=>r.count));return`<article class="card complaint-type-card"><div class="section-head"><div><span class="section-index">02 · 投诉类型占比</span><h2>${D.meta.latestCompleteWeek} 规则初分</h2><p class="subtitle">用于发现线索，不代表人工审核分类</p></div></div><div class="table-wrap"><table><thead><tr><th>投诉类型</th><th>规模</th><th>本周</th><th>占比</th><th>环比</th><th>近4周</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><span class="rank">${i+1}</span>${safe(r.name)}</td><td><div class="bar"><i style="width:${r.count/max*100}%"></i></div></td><td>${r.count}</td><td>${total?`${(r.count/total*100).toFixed(1)}%`:"—"}</td><td>${pct(change(r.count,r.last))}</td><td>${r.trend.join(" → ")}</td></tr>`).join("")}</tbody></table></div></article>`;}
  function productRows(){if(!records.length)return D.recentProductWeekly;const weeks=recentKeys(),map=new Map();scoped().filter(r=>weeks.includes(isoWeek(r.date))&&!['未填写产品','未规范产品'].includes(r.product)).forEach(r=>{const x=map.get(r.product)||[r.product,0,0,0,0,0],i=weeks.indexOf(isoWeek(r.date));x[1]++;if(i>=0)x[2+i]++;map.set(r.product,x);});return[...map.values()].sort((a,b)=>b[1]-a[1]);}
  function productTable(){const weeks=recentKeys(),rows=productRows(),total=rows.reduce((s,r)=>s+r[1],0);return`<article class="card complaint-product-card"><div class="section-head"><div><span class="section-index">03 · 产品分布</span><h2>近4个完整周已填写产品</h2><p class="subtitle">点击产品查看类型占比，再点击类型查看脱敏详情</p></div></div><div class="table-wrap"><table><thead><tr><th>产品</th><th>近4周</th><th>有效产品占比</th><th>${weeks.map(w=>w.slice(-3)).join("</th><th>")}</th><th>较上周</th><th>下钻</th></tr></thead><tbody>${rows.map((r,i)=>`<tr class="complaint-product-row" data-complaint-product="${safe(r[0])}"><td><span class="rank">${i+1}</span>${safe(r[0])}</td><td>${r[1]}</td><td>${total?`${(r[1]/total*100).toFixed(1)}%`:"—"}</td><td>${r.slice(2,6).join("</td><td>")}</td><td>${r[5]-r[4]>=0?"+":""}${r[5]-r[4]}</td><td><button class="drill" data-complaint-product="${safe(r[0])}">查看类型 ›</button></td></tr>`).join("")}</tbody></table></div><div class="muted-box">近4周共 ${recent().reduce((s,r)=>s+Number(r?.[1]||0),0)} 起，其中 ${total} 起有可用产品名称。</div></article>`;}
  const detailsFor=(product,type="")=>detailRecords.filter(r=>match(r)&&r.product===product&&(!type||r.type===type)&&recentKeys().includes(isoWeek(r.date)));
  function openProduct(product){if(!window.DASHBOARD_MODAL)return;const rows=detailsFor(product),map=new Map();rows.forEach(r=>map.set(r.type,(map.get(r.type)||0)+1));const types=[...map].sort((a,b)=>b[1]-a[1]),total=rows.length,html=`<div class="modal-summary"><span>产品 <b>${safe(product)}</b></span><span>近4周 <b>${total} 起</b></span></div><div class="table-wrap"><table><thead><tr><th>投诉类型</th><th>起数</th><th>产品内占比</th><th>下钻</th></tr></thead><tbody>${types.map((r,i)=>`<tr class="complaint-type-row" data-complaint-product="${safe(product)}" data-complaint-type="${safe(r[0])}"><td><span class="rank">${i+1}</span>${safe(r[0])}</td><td>${r[1]}</td><td>${total?`${(r[1]/total*100).toFixed(1)}%`:"—"}</td><td><button class="drill" data-complaint-product="${safe(product)}" data-complaint-type="${safe(r[0])}">查看脱敏详情 ›</button></td></tr>`).join("")}</tbody></table></div><div class="muted-box">占比分母为该产品近4个完整周的有效投诉数；类型为规则初分。</div>`;window.DASHBOARD_MODAL.open({title:`${product} · 投诉类型下钻`,subtitle:"点击类型继续查看脱敏详情",html});}
  function openDetails(product,type){const rows=detailsFor(product,type),html=`<div class="modal-summary"><span>产品 <b>${safe(product)}</b></span><span>类型 <b>${safe(type)}</b></span><span>记录 <b>${rows.length} 起</b></span></div><div class="table-wrap"><table><thead><tr><th>日期</th><th>脱敏问题标签</th><th>处理结果</th><th>工单状态</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.date}</td><td><div class="complaint-detail-tags">${r.tags.map(t=>`<span class="tag blue">${safe(t)}</span>`).join("")}</div></td><td>${r.result?'<span class="pill">已填写</span>':'<span class="tag red">未填写</span>'}</td><td>${r.status?'<span class="pill">已同步</span>':'<span class="tag red">未同步</span>'}</td></tr>`).join("")}</tbody></table></div><div class="notice">公开看板不展示原始叙述、姓名、手机号或订单号，仅展示规则提取的问题标签。</div>`;window.DASHBOARD_MODAL.open({title:`${product} · ${type}`,subtitle:"脱敏投诉详情",html,onBack:()=>openProduct(product)});}
  function lower(){const m=D.meta,missingProduct=m.missingProduct/m.recordCount*100,missingResult=m.missingResult/m.recordCount*100,missingStatus=m.missingStatus/m.recordCount*100,channel=channelUsable?`<div class="notice">关联店铺字段覆盖 ${channelCoverage.toFixed(1)}%，平台/店铺筛选已启用。</div>`:`<div class="complaint-unavailable"><strong>—</strong><p>${safe(m.storeFieldNote)}</p><small>当前覆盖 ${channelCoverage.toFixed(1)}%。筛选控件已预留，覆盖率达90%后自动启用。</small></div>`;return`<div class="grid complaint-bottom-grid"><article class="card"><span class="section-index">04 · 投诉渠道</span><h2>${channelUsable?"渠道筛选可用":"渠道分布暂不可计算"}</h2>${channel}</article><article class="card"><span class="section-index">05 · 数据质量</span><h2>影响分析的字段缺口</h2><div class="quality-grid"><div><b>产品未填写</b><strong>${m.missingProduct}</strong><p>${missingProduct.toFixed(1)}%</p></div><div><b>处理结果未填写</b><strong>${m.missingResult}</strong><p>${missingResult.toFixed(1)}%</p></div><div><b>工单状态未同步</b><strong>${m.missingStatus}</strong><p>${missingStatus.toFixed(1)}%</p></div><div><b>重复工单</b><strong>${m.duplicateTickets}</strong><p>${m.uniqueTickets}个唯一工单</p></div></div></article></div>`;}
  function conclusion(){const cur=latest(),pre=previous(),four=recent(),total=cur?.[1]||0,top=D.types.map((name,i)=>({name,count:typeCount(cur,i),last:typeCount(pre,i)})).sort((a,b)=>b.count-a.count)[0];return`<section class="complaint-conclusion"><strong>本周结论</strong><span>${D.meta.latestCompleteWeek} 投诉 ${total} 起，环比 ${pct(change(total,pre?.[1]||0))}，较近4周均值 ${pct(change(total,average(four)))}。</span><em>主要线索为“${safe(top.name)}” ${top.count} 起，较上周 ${top.count-top.last>=0?"+":""}${top.count-top.last} 起；类型为规则初分。</em></section>`;}
  function render(){refreshFilters();document.querySelectorAll("[data-complaint-grain]").forEach(b=>b.classList.toggle("active",b.dataset.complaintGrain===state.grain));scope.textContent=`${state.platform||"全部平台"} · ${state.shop||"全部店铺"} · 最新完整周 ${D.meta.latestCompleteWeek} · 数据截至 ${D.meta.sourceMax}`;renderKpis();body.innerHTML=conclusion()+`<div class="grid complaint-main-grid">${trendChart()}${typeTable()}</div>`+productTable()+lower();}
  document.addEventListener("click",e=>{const g=e.target.closest("[data-complaint-grain]");if(g){state.grain=g.dataset.complaintGrain;render();return;}const t=e.target.closest("[data-complaint-type]");if(t){openDetails(t.dataset.complaintProduct,t.dataset.complaintType);return;}const p=e.target.closest("[data-complaint-product]");if(p)openProduct(p.dataset.complaintProduct);});
  platformSelect.addEventListener("change",()=>{state.platform=platformSelect.value;state.shop="";render();});shopSelect.addEventListener("change",()=>{state.shop=shopSelect.value;render();});
  window.COMPLAINT_APP={render};render();
})();
