(() => {
  "use strict";
  const D = window.PRE_SALES_DATA;
  if (!D) return;
  const $ = s => document.querySelector(s);
  const pre = $("#preSalesWorkspace"), weekly = $("#weeklyReviewWorkspace"), after = $("#afterSalesWorkspace"), kpis = $("#preKpis"), body = $("#preDashboardBody");
  const platformSelect = $("#prePlatform"), shopSelect = $("#preShop"), rangeSelect = $("#preRange");
  const fmt = new Intl.NumberFormat("zh-CN", {maximumFractionDigits:1});
  const money = n => `¥${fmt.format(Number(n || 0))}`;
  const pct = n => Number.isFinite(n) ? `${n >= 0 ? "+" : ""}${n.toFixed(1)}%` : "—";
  const safe = s => String(s ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const state = {module:"overview", grain:"month", range:"ytd", platform:"", shop:""};
  let workspace = "pre";
  let afterSalesPromise = null;
  const loadScript = src => new Promise((resolve,reject) => { const script=document.createElement("script");script.src=src;script.onload=resolve;script.onerror=()=>reject(new Error(`加载失败：${src}`));document.head.appendChild(script); });
  function ensureAfterSales(){
    if(window.AFTER_SALES_DATA) return Promise.resolve();
    if(afterSalesPromise) return afterSalesPromise;
    $("#dataStatus").textContent="正在加载售后分析数据…";
    $("#dashboardBody").innerHTML=`<article class="card loading-card"><div class="loading-dot"></div><h2>正在加载售后数据…</h2><p class="subtitle">首次进入售后页加载，后续切换直接使用缓存。</p></article>`;
    afterSalesPromise=loadScript("../data/after-sales-data.js?v=20260821-10").then(()=>loadScript("../after-sales.js?v=20260821-12")).catch(err=>{afterSalesPromise=null;$("#dashboardBody").innerHTML=`<article class="card"><div class="empty">${safe(err.message)}，请刷新后重试。</div></article>`;throw err;});
    return afterSalesPromise;
  }

  const rows = () => state.grain === "month" ? D.month : D.week;
  const periods = () => [...new Set(rows().map(r => r.p))].sort();
  const currentPartial = () => state.grain === "month" ? D.meta.sourceMax.slice(0,7) : isoWeek(D.meta.sourceMax);
  const maxComplete = () => state.grain === "month" ? previousMonth(D.meta.commonComplete.slice(0,7)) : isoWeek(D.meta.commonComplete);
  function isoWeek(dateString){const date=new Date(`${dateString}T00:00:00Z`),day=date.getUTCDay()||7;date.setUTCDate(date.getUTCDate()+4-day);const start=new Date(Date.UTC(date.getUTCFullYear(),0,1)),week=Math.ceil((((date-start)/86400000)+1)/7);return `${date.getUTCFullYear()}-W${String(week).padStart(2,"0")}`;}
  function previousMonth(month){const [y,m]=month.split("-").map(Number),d=new Date(Date.UTC(y,m-2,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`;}
  function rangeOptions(){
    if(state.grain === "week") return [["recent4","最近4个完整周"],["recent8","最近8个完整周"],["latest","最新完整周"],["current","当前周（截至最新日）"]];
    const years=[...new Set(periods().map(p=>p.slice(0,4)))].sort().reverse();
    return [...years.map(y=>[y==="2026"?"ytd":`year-${y}`,y==="2026"?`${y}年累计（月度）`:`${y}年可用期（月度）`]),["last6","最近6个完整月"],["latest","最新完整月"],["mtd","本月至今"]];
  }
  function selectedPeriods(){const all=periods(),complete=all.filter(p=>p<=maxComplete());if(state.grain==="week"){if(state.range==="latest")return complete.slice(-1);if(state.range==="recent8")return complete.slice(-8);if(state.range==="current")return [currentPartial()];return complete.slice(-4);}if(state.range==="latest")return complete.slice(-1);if(state.range==="last6")return complete.slice(-6);if(state.range==="mtd")return [currentPartial()];const year=state.range.startsWith("year-")?state.range.slice(5):"2026";return all.filter(p=>p.startsWith(year));}
  function previousPeriods(list){const all=periods(),i=all.indexOf(list[0]);return i<0?[]:all.slice(Math.max(0,i-list.length),i);}
  function filtered(periodList=selectedPeriods(), extra={}){const set=new Set(periodList),platform=extra.platform??state.platform,shop=extra.shop??state.shop;return rows().filter(r=>set.has(r.p)&&(!platform||r.pf===platform)&&(!shop||r.s===shop));}
  function combine(list){const x={consult:0,sales:0,converted:0,inquiryBase:0,storeSalesBase:0,shareSales:0,shareDays:0,fw:0,fn:0,aw:0,an:0,days:0};list.forEach(r=>{x.consult+=r.c||0;x.sales+=r.a||0;x.converted+=r.t||0;x.inquiryBase+=r.ib||0;x.storeSalesBase+=r.sb||0;x.shareSales+=r.sa||0;x.shareDays+=r.sd||0;x.fw+=r.fw||0;x.fn+=r.fn||0;x.aw+=r.aw||0;x.an+=r.an||0;x.days+=r.d||0;});x.conversion=x.inquiryBase?x.converted/x.inquiryBase*100:NaN;x.salesShareCoverage=x.days?x.shareDays/x.days*100:0;x.salesShare=x.storeSalesBase&&x.salesShareCoverage>=90?x.shareSales/x.storeSalesBase*100:NaN;x.consultConversion=x.consult?x.converted/x.consult*100:NaN;x.salesPerConsult=x.consult?x.sales/x.consult:NaN;x.first=x.fn?x.fw/x.fn:NaN;x.avg=x.an?x.aw/x.an:NaN;x.daily=x.days?x.consult/x.days:NaN;return x;}
  const change=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)&&b!==0?(a/b-1)*100:NaN;
  const card=(label,value,note)=>`<article class="kpi"><span class="label">${label}</span><strong>${value}</strong><small>${note}</small></article>`;
  function refreshControls(){
    platformSelect.innerHTML=`<option value="">全部平台</option>`+D.meta.platforms.map(x=>`<option value="${safe(x)}">${safe(x)}</option>`).join("");platformSelect.value=state.platform;
    const shops=D.meta.shops.filter(shop=>!state.platform||D.month.some(r=>r.pf===state.platform&&r.s===shop));
    if(state.shop&&!shops.includes(state.shop))state.shop="";
    shopSelect.innerHTML=`<option value="">全部店铺</option>`+shops.map(x=>`<option value="${safe(x)}">${safe(x)}</option>`).join("");shopSelect.value=state.shop;
    const options=rangeOptions();if(!options.some(x=>x[0]===state.range))state.range=options[0][0];rangeSelect.innerHTML=options.map(([v,l])=>`<option value="${v}">${l}</option>`).join("");rangeSelect.value=state.range;
    document.querySelectorAll("[data-pre-grain]").forEach(b=>b.classList.toggle("active",b.dataset.preGrain===state.grain));
    document.querySelectorAll("[data-pre-module]").forEach(b=>b.classList.toggle("active",b.dataset.preModule===state.module));
  }
  function renderKpis(){const cur=combine(filtered()),prev=combine(filtered(previousPeriods(selectedPeriods()))),comparable=previousPeriods(selectedPeriods()).length===selectedPeriods().length;let cards;
    if(state.module==="conversion") cards=[["询单成交人数",fmt.format(cur.converted),comparable?`较上期 ${pct(change(cur.converted,prev.converted))}`:"当前筛选期"],["询单转化率",Number.isFinite(cur.conversion)?`${cur.conversion.toFixed(1)}%`:"—","按每日填报转化率加权估算"],["客服销售占比",Number.isFinite(cur.salesShare)?`${cur.salesShare.toFixed(1)}%`:"—","客服销售额 ÷ 反推店铺销售额"],["每次咨询产值",money(cur.salesPerConsult),comparable?`较上期 ${pct(change(cur.salesPerConsult,prev.salesPerConsult))}`:"客服净销售额 ÷ 咨询人数"]];
    else if(state.module==="service") cards=[["首次响应",Number.isFinite(cur.first)?`${cur.first.toFixed(1)}秒`:"—",comparable?`较上期 ${pct(change(cur.first,prev.first))}`:"越低越好"],["平均响应",Number.isFinite(cur.avg)?`${cur.avg.toFixed(1)}秒`:"—",comparable?`较上期 ${pct(change(cur.avg,prev.avg))}`:"越低越好"],["日均咨询人数",fmt.format(cur.daily),"总咨询人数 ÷ 有效填报天数"],["询单转化率",Number.isFinite(cur.conversion)?`${cur.conversion.toFixed(1)}%`:"—","用于判断速度改善是否带来转化"]];
    else if(state.module==="audit") cards=[["原始记录",fmt.format(D.meta.rawRows),"客服日维度"],["重复日组",fmt.format(D.meta.duplicateGroups),"已从工作台汇总中剔除"],["空指标行",fmt.format(D.meta.blankRows),"不计入经营合计"],["退款率异常",fmt.format(D.meta.refundAnomalies),"大于100%，待确认口径"]];
    else cards=[["总咨询人数",fmt.format(cur.consult),comparable?`较上期 ${pct(change(cur.consult,prev.consult))}`:"当前筛选期"],["客服净销售额",money(cur.sales),comparable?`较上期 ${pct(change(cur.sales,prev.sales))}`:"去退后客服销售额"],["询单转化率",Number.isFinite(cur.conversion)?`${cur.conversion.toFixed(1)}%`:"—","各店铺原表口径加权估算"],["每次咨询产值",money(cur.salesPerConsult),comparable?`较上期 ${pct(change(cur.salesPerConsult,prev.salesPerConsult))}`:"衡量咨询的销售产出"]];
    kpis.innerHTML=cards.map(x=>card(...x)).join("");
  }
  function series(){return selectedPeriods().map(p=>({p,m:combine(filtered([p]))}));}
  function tooltipCompare(list,index,key){const value=list[index].m[key],prev=index?list[index-1].m[key]:NaN;let yoy=NaN;if(state.grain==="month"){const target=`${Number(list[index].p.slice(0,4))-1}-${list[index].p.slice(5)}`,row=rows().filter(r=>r.p===target);if(row.length)yoy=change(value,combine(row.filter(r=>(!state.platform||r.pf===state.platform)&&(!state.shop||r.s===state.shop)))[key]);}return {mom:change(value,prev),yoy};}
  function trendChart(config){const list=series();if(!list.length)return `<div class="empty">当前筛选无趋势数据</div>`;const W=1000,H=390,L=65,R=60,T=55,B=55,iw=W-L-R,ih=H-T-B,a=list.map(x=>x.m[config.a]),b=list.map(x=>x.m[config.b]),amax=Math.max(1,...a.filter(Number.isFinite)),bmax=Math.max(1,...b.filter(Number.isFinite)),x=i=>L+(list.length===1?iw/2:i*iw/(list.length-1)),y=(v,max)=>T+ih-v/max*ih,path=(arr,max)=>arr.map((v,i)=>Number.isFinite(v)?`${i===0||!Number.isFinite(arr[i-1])?"M":"L"}${x(i)},${y(v,max)}`:"").join(" ");let svg=`<div class="legend"><span><i></i>${config.aLabel}</span><span><i class="green"></i>${config.bLabel}</span></div><svg class="trend-svg" viewBox="0 0 ${W} ${H}">`;
    for(let i=0;i<4;i++){const gy=T+i*ih/3;svg+=`<line x1="${L}" y1="${gy}" x2="${W-R}" y2="${gy}" stroke="var(--line)"/>`;}
    svg+=`<text x="${L}" y="${T-10}" fill="var(--muted)" font-size="12">${safe(config.aAxis(amax))}</text><text x="${W-R}" y="${T-10}" text-anchor="end" fill="var(--muted)" font-size="12">${safe(config.bAxis(bmax))}</text><path d="${path(a,amax)}" fill="none" stroke="var(--red)" stroke-width="4"/><path d="${path(b,bmax)}" fill="none" stroke="var(--green)" stroke-width="4" stroke-dasharray="10 8"/>`;
    list.forEach((item,i)=>{const ca=tooltipCompare(list,i,config.a),cb=tooltipCompare(list,i,config.b),tip=safe(JSON.stringify({period:item.p,a:a[i],b:b[i],aLabel:config.aLabel,bLabel:config.bLabel,aFmt:config.aFmt(a[i]),bFmt:config.bFmt(b[i]),aMom:ca.mom,aYoy:ca.yoy,bMom:cb.mom,bYoy:cb.yoy,partial:item.p===currentPartial()}));svg+=`<text x="${x(i)}" y="${H-18}" text-anchor="middle" fill="var(--muted)" font-size="13">${safe(item.p.replace(/^\d{4}-/,""))}</text>`;if(Number.isFinite(a[i]))svg+=`<g class="pre-chart-node" data-pre-tip="${tip}"><circle cx="${x(i)}" cy="${y(a[i],amax)}" r="6" fill="white" stroke="var(--red)" stroke-width="4"/><text x="${x(i)}" y="${Math.max(17,y(a[i],amax)-11)}" text-anchor="middle" fill="var(--red)" font-size="12" font-weight="800">${safe(config.aShort(a[i]))}</text></g>`;if(Number.isFinite(b[i]))svg+=`<g class="pre-chart-node" data-pre-tip="${tip}"><circle cx="${x(i)}" cy="${y(b[i],bmax)}" r="6" fill="white" stroke="var(--green)" stroke-width="4"/><text x="${x(i)}" y="${Math.min(H-B+28,y(b[i],bmax)+19)}" text-anchor="middle" fill="var(--green)" font-size="12" font-weight="800">${safe(config.bShort(b[i]))}</text></g>`;});return svg+`</svg><div class="notice">售前数据 ${D.meta.sourceMin} 至 ${D.meta.sourceMax}，跨店铺共同完整截止日 ${D.meta.commonComplete}。本月/当前周为部分周期，不建议与完整周期直接比较。</div>`;}
  const configs={overview:{a:"consult",b:"salesPerConsult",aLabel:"红色实线：咨询人数",bLabel:"绿色虚线：每次咨询产值",aAxis:n=>`咨询 0–${fmt.format(n)}`,bAxis:n=>`产值 0–¥${n.toFixed(1)}`,aFmt:n=>fmt.format(n),bFmt:n=>money(n),aShort:n=>fmt.format(n),bShort:n=>`¥${n.toFixed(1)}`},conversion:{a:"conversion",b:"salesShare",aLabel:"红色实线：询单转化率",bLabel:"绿色虚线：客服销售占比",aAxis:n=>`转化率 0–${n.toFixed(1)}%`,bAxis:n=>`贡献 0–${n.toFixed(1)}%`,aFmt:n=>`${n.toFixed(1)}%`,bFmt:n=>`${n.toFixed(1)}%`,aShort:n=>`${n.toFixed(1)}%`,bShort:n=>`${n.toFixed(1)}%`},service:{a:"first",b:"avg",aLabel:"红色实线：首次响应时长",bLabel:"绿色虚线：平均响应时长",aAxis:n=>`首响 0–${n.toFixed(1)}秒`,bAxis:n=>`平均 0–${n.toFixed(1)}秒`,aFmt:n=>`${n.toFixed(1)}秒`,bFmt:n=>`${n.toFixed(1)}秒`,aShort:n=>n.toFixed(1),bShort:n=>n.toFixed(1)}};
  function table(headers,rows,min="820px"){return `<div class="table-wrap"><table style="min-width:${min}"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`;}
  function ranking(){const key=state.platform?"s":"pf",items=[...new Set(filtered().map(r=>r[key]))].map(name=>{const opts=key==="s"?{shop:name}:{platform:name,shop:""};return {name,...combine(filtered(selectedPeriods(),opts))};}).sort((a,b)=>b.sales-a.sales);return table([state.platform?"店铺":"平台","咨询人数","客服净销售额","询单转化率","销售占比","咨询产值","首次响应","平均响应"],items.map((x,i)=>`<tr><td><span class="rank">${i+1}</span>${safe(x.name)}</td><td>${fmt.format(x.consult)}</td><td>${money(x.sales)}</td><td>${Number.isFinite(x.conversion)?x.conversion.toFixed(1)+"%":"—"}</td><td>${Number.isFinite(x.salesShare)?x.salesShare.toFixed(1)+"%":`<span title="有效数据完整率 ${x.salesShareCoverage.toFixed(1)}%">—</span>`}</td><td>${money(x.salesPerConsult)}</td><td>${Number.isFinite(x.first)?x.first.toFixed(1)+"秒":"—"}</td><td>${Number.isFinite(x.avg)?x.avg.toFixed(1)+"秒":"—"}</td></tr>`),"1080px");}
  function insight(){const list=series(),complete=list.filter(x=>x.p<=maxComplete()),cur=complete.at(-1)?.m,prev=complete.at(-2)?.m;if(!cur||!prev)return "当前可比周期不足，暂不生成经营判断。";const q=change(cur.consult,prev.consult),s=change(cur.sales,prev.sales),v=change(cur.salesPerConsult,prev.salesPerConsult),c=cur.conversion-prev.conversion,r=cur.avg-prev.avg;const points=[];if(q>0&&s<0)points.push(`咨询量增长 ${pct(q)}，但客服销售额下降 ${pct(s)}，应优先查流量质量、产品价格与话术`);if(v<-5)points.push(`每次咨询产值下降 ${pct(v)}，咨询增长未转化为等比例产出`);if(r<0&&c<0)points.push(`平均响应已改善 ${Math.abs(r).toFixed(1)} 秒，但转化率仍下降 ${Math.abs(c).toFixed(1)} 个百分点，不建议只用增加人力解决`);if(!points.length)points.push(`最新完整周期销售额 ${pct(s)}、询单转化率 ${c>=0?"+":""}${c.toFixed(1)} 个百分点，暂无明显“量增效降”信号`);return points.map(x=>`<li>${x}</li>`).join("");}
  function renderAudit(){const d=D.audit.duplicates,r=D.audit.refundAnomalies.slice().sort((a,b)=>b.value-a.value);body.innerHTML=`<div class="grid equal"><article class="card"><h2>重复与空行备查</h2><p class="subtitle">重复日数据不自动猜测保留项，已从正式汇总剔除</p>${table(["重复键","来源行"],d.map(x=>`<tr><td>${safe(x.key)}</td><td>${x.rows.join("、")}</td></tr>`))}<div class="muted-box">另有 ${D.audit.blankRows.length} 行核心指标为空，未计入经营汇总。</div></article><article class="card"><h2>退款率异常备查</h2><p class="subtitle">原表数值大于100%，当前不用于绩效排名</p>${table(["日期 / 店铺","退款率","来源行"],r.map(x=>`<tr><td>${x.date}<br><small>${safe(x.platform)} / ${safe(x.shop)}</small></td><td class="bad">${x.value.toFixed(2)}%</td><td>${x.sourceRow}</td></tr>`))}</article></div>`;}
  function render(){renderKpis();if(state.module==="audit"){renderAudit();return;}const cfg=configs[state.module],title=state.module==="overview"?"客服工作量与咨询产值趋势":state.module==="conversion"?"询单转化与销售贡献趋势":"响应时长与服务负荷";body.innerHTML=`<div class="grid"><article class="card"><h2>${title}</h2><p class="subtitle">节点显示当期数值，悬停可看环比与同比</p>${trendChart(cfg)}</article><article class="card"><h2>${state.platform?"店铺":"平台"}经营排名</h2><p class="subtitle">默认按客服净销售额降序，同时看转化、产值和响应</p>${ranking()}</article></div><article class="card manager-insight"><h2>经营观察与改善建议</h2><ul>${insight()}</ul><div class="muted-box">询单转化率和客服销售占比由每日填报百分比反推分母后加权，适合经营趋势判断；要做精确复盘，还需要原表补充“实际询单人数”和“店铺销售额”。</div></article>`;bindTips();}
  function bindTips(){const tip=$("#tooltip");document.querySelectorAll("[data-pre-tip]").forEach(node=>{node.onmouseenter=()=>{const d=JSON.parse(node.dataset.preTip),line=(label,value,mom,yoy)=>`${label}：${value}<br>环比：${pct(mom)}${state.grain==="month"?` ｜ 同比：${pct(yoy)}`:""}`;tip.innerHTML=`<b>${safe(d.period)}${d.partial?" · 部分周期":""}</b><br>${line(d.aLabel,d.aFmt,d.aMom,d.aYoy)}<br>${line(d.bLabel,d.bFmt,d.bMom,d.bYoy)}`;tip.style.display="block";};node.onmousemove=e=>{tip.style.left=`${e.clientX+14}px`;tip.style.top=`${e.clientY+14}px`;};node.onmouseleave=()=>tip.style.display="none";});}
  function updateStatus(){if(workspace==="pre")$("#dataStatus").textContent=`售前 ${D.meta.sourceMin} 至 ${D.meta.sourceMax} · 各店共同完整至 ${D.meta.commonComplete} · 已自动剔除重复日与空行 · 页面版本 v15`;else if(workspace==="weekly")$("#dataStatus").textContent=`上周复盘 · 自动选择售前、售后与销售共同完整周 · 页面版本 v15`;else if(window.AFTER_SALES_DATA)$("#dataStatus").textContent=`售后 ${window.AFTER_SALES_DATA.meta.afterSalesMin} 至 ${window.AFTER_SALES_DATA.meta.afterSalesMax} · 销售至 ${window.AFTER_SALES_DATA.meta.salesMax} · 页面版本 v15`;}
  function refresh(){refreshControls();render();updateStatus();}
  if(!window.CS_THEME_BOUND){window.CS_THEME_BOUND=true;$("#themeBtn").addEventListener("click",()=>{document.body.classList.toggle("dark");$("#themeBtn").textContent=document.body.classList.contains("dark")?"浅色模式":"深色模式";});}
  document.addEventListener("click",async e=>{const w=e.target.closest("[data-workspace]");if(w){workspace=w.dataset.workspace;pre.hidden=workspace!=="pre";weekly.hidden=workspace!=="weekly";after.hidden=workspace!=="after";document.querySelectorAll("[data-workspace]").forEach(b=>b.classList.toggle("active",b.dataset.workspace===workspace));if(workspace==="after"||workspace==="weekly"){try{await ensureAfterSales();}catch{return;}}if(workspace==="weekly")window.WEEKLY_REVIEW_APP?.render();updateStatus();return;}const m=e.target.closest("[data-pre-module]");if(m){state.module=m.dataset.preModule;refresh();return;}const g=e.target.closest("[data-pre-grain]");if(g){state.grain=g.dataset.preGrain;state.range=state.grain==="week"?"recent4":"ytd";refresh();return;}});
  document.addEventListener("change",e=>{if(e.target===platformSelect){state.platform=e.target.value;state.shop="";refresh();}if(e.target===shopSelect){state.shop=e.target.value;refresh();}if(e.target===rangeSelect){state.range=e.target.value;refresh();}});
  refresh();
})();
