(()=>{
'use strict';
const categories=window.REVIEW_INSIGHTS||[],manifest=window.REVIEW_MANIFEST,cache={},loads=new Map(),colors=['#1877f2','#8b5cf6','#18a77b','#f59e0b','#ef5b5b','#25a4c4','#d946ef','#64748b'];
const saved=(()=>{try{return JSON.parse(localStorage.getItem('vocDateRange')||'{}')}catch{return {}}})();
const clamp=(value,min,max)=>value&&value>=min&&value<=max?value:null;
const state={category:0,start:clamp(saved.start,manifest?.minDate,manifest?.maxDate)||manifest?.minDate||'',end:clamp(saved.end,manifest?.minDate,manifest?.maxDate)||manifest?.maxDate||'',metric:'good',stores:new Set(),autoStores:true};
if(state.start>state.end)[state.start,state.end]=[state.end,state.start];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('zh-CN');
const pct=v=>v==null?'—':`${v.toFixed(1)}%`;
const current=()=>categories[state.category];
const data=()=>cache[current()?.name]||{ratings:[],ratingShops:[]};
const fullRange=()=>state.start===manifest?.minDate&&state.end===manifest?.maxDate;
const inRange=r=>r.date>=state.start&&r.date<=state.end;
const rows=()=>data().ratings.filter(inRange);
function summary(list){const total=list.length,good=list.filter(r=>r.rating==='好评').length,neutral=list.filter(r=>r.rating==='中评').length,bad=list.filter(r=>r.rating==='差评').length,labeled=good+neutral+bad;return {total,labeled,good,neutral,bad,coverage:total?labeled*100/total:0,goodRate:labeled?good*100/labeled:null,neutralRate:labeled?neutral*100/labeled:null,badRate:labeled?bad*100/labeled:null}}
function storeRows(){const grouped=new Map();rows().forEach(r=>{if(!grouped.has(r.shop))grouped.set(r.shop,[]);grouped.get(r.shop).push(r)});return [...grouped].map(([shop,list])=>({shop,...summary(list)})).sort((a,b)=>b.labeled-a.labeled||b.total-a.total||a.shop.localeCompare(b.shop,'zh-CN'))}
async function load(){const name=current().name;if(cache[name])return;if(loads.has(name))return loads.get(name);const file=manifest?.categories?.[name];if(!file)throw new Error(`缺少${name}数据映射`);const task=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=`data/${file}?v=20260820-2`;s.onload=()=>{const payload=window.REVIEW_CATEGORY_DATA?.[name];s.remove();if(!payload)return reject(new Error(`${name}数据无效`));cache[name]=payload;delete window.REVIEW_CATEGORY_DATA[name];resolve()};s.onerror=()=>{s.remove();reject(new Error(`${name}数据加载失败`))};document.head.appendChild(s)}).finally(()=>loads.delete(name));loads.set(name,task);return task}
function saveRange(){localStorage.setItem('vocDateRange',JSON.stringify({start:state.start,end:state.end}))}
function setDates(start,end){state.start=start;state.end=end;if(state.start>state.end)[state.start,state.end]=[state.end,state.start];state.autoStores=true;saveRange();render()}
function ensureStores(stores){const available=new Set(stores.map(x=>x.shop));state.stores=new Set([...state.stores].filter(x=>available.has(x)));if(state.autoStores){state.stores=new Set(stores.slice(0,5).map(x=>x.shop));state.autoStores=false}}
function sidebar(stores){
  ensureStores(stores);
  document.getElementById('ratingSidebar').innerHTML=`<nav class="page-switch" aria-label="看板页面"><a href="dashboard-v3.html">VOC洞察</a><a class="active" href="rating-dashboard.html">店铺好评</a><a href="attention-dashboard.html">关注点</a></nav><div class="sidebar-label important">1. 选择品类（必选）</div><div class="category-list rating-category-list">${categories.map((c,i)=>`<button class="cat-button" data-category="${i}" aria-current="${i===state.category}"><span>${esc(c.name)}</span><small>›</small></button>`).join('')}</div><div class="sidebar-label important">2. 时间范围</div><div class="side-filter"><div class="date-range"><span><small>开始日期</small><input type="date" id="startDate" min="${manifest.minDate}" max="${manifest.maxDate}" value="${state.start}"></span><i>至</i><span><small>结束日期</small><input type="date" id="endDate" min="${manifest.minDate}" max="${manifest.maxDate}" value="${state.end}"></span></div><div class="date-presets"><button data-days="all" class="${fullRange()?'active':''}">全部</button><button data-days="28">近4周</button><button data-days="84">近12周</button><button data-days="ytd">今年</button></div></div><div class="sidebar-label important">3. 对比店铺</div><div class="store-tools"><button id="topStores">前5店铺</button><button id="clearStores">清空</button></div><div class="store-checks">${stores.length?stores.map((s,i)=>`<label><input type="checkbox" value="${esc(s.shop)}" ${state.stores.has(s.shop)?'checked':''}><i style="--store-color:${colors[i%colors.length]}"></i><span title="${esc(s.shop)}">${esc(s.shop)}</span><small>${fmt(s.labeled)}条标注</small></label>`).join(''):'<p>当前范围无店铺数据</p>'}</div>`;
  document.querySelectorAll('[data-category]').forEach(b=>b.onclick=async()=>{state.category=+b.dataset.category;state.stores.clear();state.autoStores=true;loading();try{await load();render()}catch(e){failure(e.message)}});
  document.getElementById('startDate').onchange=e=>setDates(e.target.value,state.end);
  document.getElementById('endDate').onchange=e=>setDates(state.start,e.target.value);
  document.querySelectorAll('.date-presets button').forEach(b=>b.onclick=()=>{const v=b.dataset.days,end=new Date(`${manifest.maxDate}T00:00:00Z`);if(v==='all')return setDates(manifest.minDate,manifest.maxDate);if(v==='ytd')return setDates(`${end.getUTCFullYear()}-01-01`,manifest.maxDate);const start=new Date(end);start.setUTCDate(start.getUTCDate()-Number(v)+1);setDates(start.toISOString().slice(0,10),manifest.maxDate)});
  document.querySelectorAll('.store-checks input').forEach(input=>input.onchange=()=>{input.checked?state.stores.add(input.value):state.stores.delete(input.value);state.autoStores=false;render()});
  document.getElementById('topStores').onclick=()=>{state.stores=new Set(stores.slice(0,5).map(x=>x.shop));state.autoStores=false;render()};
  document.getElementById('clearStores').onclick=()=>{state.stores.clear();state.autoStores=false;render()};
}
function metricValue(s){return state.metric==='good'?s.goodRate:state.metric==='neutral'?s.neutralRate:s.badRate}
function monday(date){const d=new Date(`${date}T00:00:00Z`),day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()-day+1);return d.toISOString().slice(0,10)}
function addDays(date,n){const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function shortDate(date){return `${Number(date.slice(5,7))}/${Number(date.slice(8,10))}`}
function weeklySeries(){const allWeeks=[];for(let start=monday(state.start);start<=state.end;start=addDays(start,7)){const end=addDays(start,6),partial=start<state.start||end>state.end;allWeeks.push({start,end,key:start,label:`${shortDate(start)}–${shortDate(end)}${partial?'*':''}`,partial})}const selected=[...state.stores],allByShop=new Map(selected.map(shop=>[shop,allWeeks.map(w=>{const list=rows().filter(r=>r.shop===shop&&monday(r.date)===w.key),s=summary(list),tier=s.labeled>=30?'strong':s.labeled>=10?'low':'none';return {...s,tier,value:tier==='none'?null:metricValue(s)}})])),active=[];allByShop.forEach(values=>values.forEach((point,i)=>{if(point.value!=null)active.push(i)}));let first=0,last=allWeeks.length-1;if(active.length){first=Math.max(0,Math.min(...active)-1);last=Math.min(allWeeks.length-1,Math.max(...active)+1)}else if(allWeeks.length>12)first=allWeeks.length-12;const weeks=allWeeks.slice(first,last+1),byShop=new Map(selected.map(shop=>[shop,(allByShop.get(shop)||[]).slice(first,last+1)])),displayStart=weeks.length?(weeks[0].start<state.start?state.start:weeks[0].start):state.start,displayEnd=weeks.length?(weeks.at(-1).end>state.end?state.end:weeks.at(-1).end):state.end;return {weeks,byShop,displayStart,displayEnd,focused:first>0||last<allWeeks.length-1}}
function chartScale(series){const values=[];series.byShop.forEach(points=>points.forEach(point=>{if(point.value!=null)values.push(point.value)}));if(!values.length)return {min:0,max:100,ticks:5,adaptive:false};const low=Math.min(...values),high=Math.max(...values);if(state.metric==='good'){if(low>=80)return {min:80,max:100,ticks:4,adaptive:true};if(low>=60)return {min:60,max:100,ticks:4,adaptive:true};return {min:0,max:100,ticks:5,adaptive:false}}const max=Math.min(100,Math.max(10,Math.ceil((high+2)/10)*10));return {min:0,max,ticks:max<=10?5:4,adaptive:max<100}}
function renderKpis(s){const cards=[['原始评论',fmt(s.total),'当前筛选范围'],['已标注评价',fmt(s.labeled),`覆盖率 ${pct(s.coverage)}`],['好评率',pct(s.goodRate),'好评 ÷ 已标注'],['中评率',pct(s.neutralRate),'中评 ÷ 已标注'],['差评率',pct(s.badRate),'差评 ÷ 已标注'],['可比店铺',fmt(storeRows().filter(x=>x.labeled>=30).length),'≥30条已标注']];return `<section class="rating-kpis">${cards.map((x,i)=>`<div class="card kpi-card kpi-${i}"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}</section>`}
function rankingTable(stores){return `<section class="card rating-table-card"><div class="section-head"><div><h2>店铺评价率排名</h2><p>仅对当前品类内的店铺排序；点击表头指标按钮切换周度趋势</p></div><span>${stores.length}家店铺</span></div><div class="table-scroll"><table class="rating-table"><thead><tr><th>店铺</th><th>原始评论</th><th>已标注</th><th>覆盖率</th><th>好评率</th><th>中评率</th><th>差评率</th><th>判断</th></tr></thead><tbody>${stores.map((s,i)=>{const enough=s.labeled>=30;return `<tr><td><i style="--store-color:${colors[i%colors.length]}"></i><b>${esc(s.shop)}</b></td><td>${fmt(s.total)}</td><td>${fmt(s.labeled)}</td><td><span class="coverage-bar"><u style="width:${Math.min(100,s.coverage)}%"></u></span>${pct(s.coverage)}</td><td class="good-cell">${enough?pct(s.goodRate):'—'}</td><td>${enough?pct(s.neutralRate):'—'}</td><td class="bad-cell">${enough?pct(s.badRate):'—'}</td><td><span class="confidence ${enough?'ok':'low'}">${s.labeled>=100?'稳定':enough?'可用':'样本不足'}</span></td></tr>`}).join('')||'<tr><td colspan="8" class="empty-cell">当前品类与日期范围没有评论</td></tr>'}</tbody></table></div></section>`}
function chartCard(series,stores){const selected=stores.filter(s=>state.stores.has(s.shop)),scale=chartScale(series),yNote=`纵轴 ${scale.min}%–${scale.max}%${scale.adaptive?' · 自适应':''}`;return `<section class="card rating-chart-card"><div class="section-head chart-title"><div><h2>店铺周度趋势</h2><p>周一至周日；带 * 为筛选边界内的不完整周；低样本周以虚线提示</p><span class="axis-scope">横轴展示 ${series.displayStart} 至 ${series.displayEnd}${series.focused?' · 已聚焦有效周':''}</span><span class="axis-scope y-axis">${yNote}</span></div><div class="metric-tabs" role="group" aria-label="趋势指标">${[['good','好评率'],['neutral','中评率'],['bad','差评率']].map(x=>`<button data-metric="${x[0]}" class="${state.metric===x[0]?'active':''}">${x[1]}</button>`).join('')}</div></div><div class="chart-legend">${selected.map((s,i)=>`<span><i style="--store-color:${colors[i%colors.length]}"></i>${esc(s.shop)}<small>${fmt(s.labeled)}条标注</small></span>`).join('')||'<em>请在左侧选择至少一家店铺</em>'}</div><div class="sample-key"><span><i class="solid"></i>≥30条：稳定实线</span><span><i class="dashed"></i>10–29条：低样本虚线</span><span><i class="blank"></i>&lt;10条：留空</span></div><div class="rating-canvas-wrap"><canvas id="ratingChart" role="img" aria-label="${esc(current().name)}店铺${state.metric==='good'?'好评率':state.metric==='neutral'?'中评率':'差评率'}周度趋势，横轴${series.displayStart}至${series.displayEnd}，纵轴${scale.min}%至${scale.max}%"></canvas></div><div class="chart-footnote"><b>判读提醒：</b>曲线经过平滑处理；虚线仅用于观察方向，不参与稳定结论。${scale.min>0?`纵轴从${scale.min}%开始而非0%，用于放大高位区间差异，请结合刻度判断。`:'纵轴从0%开始并按实际数据调整上限。'} 横轴聚焦不会改变上方指标与排名的筛选口径。</div></section>`}
function drawChart(series,stores){const canvas=document.getElementById('ratingChart');if(!canvas)return;const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=rect.width,h=rect.height;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const x=canvas.getContext('2d');x.scale(dpr,dpr);const css=getComputedStyle(document.documentElement),muted=css.getPropertyValue('--muted').trim(),line=css.getPropertyValue('--line').trim(),panel=css.getPropertyValue('--panel').trim(),scale=chartScale(series),pad={l:48,r:18,t:20,b:52},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,n=Math.max(1,series.weeks.length-1),toY=value=>pad.t+ch*(1-(value-scale.min)/(scale.max-scale.min));x.clearRect(0,0,w,h);x.font='11px system-ui';x.textAlign='right';x.textBaseline='middle';for(let i=0;i<=scale.ticks;i++){const value=scale.min+(scale.max-scale.min)*i/scale.ticks,y=toY(value);x.setLineDash([]);x.strokeStyle=line;x.lineWidth=1;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.fillStyle=muted;x.fillText(`${Number.isInteger(value)?value:value.toFixed(1)}%`,pad.l-8,y)}const step=Math.max(1,Math.ceil(series.weeks.length/8));series.weeks.forEach((week,i)=>{if(i%step&&i!==series.weeks.length-1)return;const px=pad.l+cw*(i/n);x.save();x.translate(px,h-pad.b+12);x.rotate(-.45);x.textAlign='right';x.fillStyle=muted;x.fillText(week.label,0,0);x.restore()});const selected=stores.filter(s=>state.stores.has(s.shop));selected.forEach((store,colorIndex)=>{const values=series.byShop.get(store.shop)||[],color=colors[colorIndex%colors.length];for(let i=1;i<values.length;i++){const a=values[i-1],b=values[i];if(a.value==null||b.value==null)continue;const ax=pad.l+cw*((i-1)/n),ay=toY(a.value),bx=pad.l+cw*(i/n),by=toY(b.value),low=a.tier==='low'||b.tier==='low',bend=(bx-ax)*.42;x.setLineDash(low?[7,5]:[]);x.strokeStyle=color;x.lineWidth=low?2:2.5;x.beginPath();x.moveTo(ax,ay);x.bezierCurveTo(ax+bend,ay,bx-bend,by,bx,by);x.stroke()}values.forEach((point,i)=>{if(point.value==null)return;const px=pad.l+cw*(i/n),py=toY(point.value),low=point.tier==='low';x.setLineDash(low?[3,3]:[]);x.beginPath();x.arc(px,py,low?4:3.5,0,Math.PI*2);x.fillStyle=low?panel:color;x.fill();x.strokeStyle=color;x.lineWidth=low?2:1.5;x.stroke()});x.setLineDash([])})}
function render(){const stores=storeRows();sidebar(stores);const all=summary(rows()),series=weeklySeries();document.getElementById('ratingDetail').innerHTML=`<section class="card rating-hero"><div><span>当前比较品类</span><h1>${esc(current().name)}</h1><p>${state.start} 至 ${state.end} · 仅比较本品类店铺</p></div><div class="rating-hero-rule"><b>好评率口径</b><strong>好评 ÷ 已标注评价</strong><small>未标注评价仅进入覆盖率，不进入好/中/差评率分母</small></div></section>${renderKpis(all)}${all.labeled?chartCard(series,stores):`<section class="card coverage-empty"><i>!</i><div><h2>当前品类没有可用的评价类型标签</h2><p>仍保留原始评论量与店铺分布，但不计算好评率。后续如果补齐“评价类型”字段，页面会自动恢复率值。</p></div></section>`}${rankingTable(stores)}<section class="card methodology-note"><b>数据完整性</b><p>当前 <strong>${esc(current().name)}</strong> 共 ${fmt(all.total)} 条原始评论，其中 ${fmt(all.labeled)} 条有评价类型，标签覆盖率为 ${pct(all.coverage)}。率值只代表已标注部分，不能直接外推到未标注评论。</p></section>`;document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{state.metric=b.dataset.metric;render()});requestAnimationFrame(()=>drawChart(series,stores))}
function loading(){document.getElementById('ratingDetail').innerHTML='<section class="card load-state"><div class="loader"></div><h2>正在加载店铺评价数据</h2></section>'}
function failure(message){document.getElementById('ratingDetail').innerHTML=`<section class="card load-state error-state" role="alert"><div class="error-icon">!</div><h2>评价数据加载失败</h2><p>${esc(message)}。页面不会把加载失败显示为零值。</p><button class="retry-button" onclick="location.reload()">重新加载</button></section>`}
async function start(){try{if(window.__VOC_MANIFEST_ERROR__||!manifest?.categories)throw new Error('数据清单加载失败');loading();await load();render()}catch(e){failure(e.message)}document.getElementById('themeBtn').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';document.getElementById('themeBtn').textContent=dark?'深色模式':'浅色模式';render()}}
start();
})();
