(() => {
  "use strict";
  const $ = s => document.querySelector(s);
  const fmt = new Intl.NumberFormat("zh-CN", {maximumFractionDigits:1});
  const money = n => `¥${fmt.format(Number(n || 0))}`;
  const safe = s => String(s ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const sum = (rows,key) => rows.reduce((a,r)=>a+Number(r[key]||0),0);
  const change = (a,b) => Number.isFinite(a)&&Number.isFinite(b)&&b!==0?(a/b-1)*100:NaN;
  const pct = n => Number.isFinite(n)?`${n>=0?"+":""}${n.toFixed(1)}%`:"—";
  const pp = n => Number.isFinite(n)?`${n>=0?"+":""}${n.toFixed(1)}pp`:"—";
  const cls = n => Number.isFinite(n)?(n>0?"up":"down"):"muted";
  const reviewContext = {pre:{periods:[], common:[], current:""},after:{periods:[], common:[], current:""}};
  const returnReviewSort = {key:"score", direction:"desc"};
  const drillAttrs = (kind,metric,name="",code="") => `data-review-drill data-review-kind="${safe(kind)}" data-review-metric="${safe(metric)}" data-review-name="${safe(name)}" data-review-code="${safe(code)}"`;
  const drillCell = (html,kind,metric,name="",code="",className="") => `<td class="review-drill-value ${className}" ${drillAttrs(kind,metric,name,code)}>${html}</td>`;

  function preAgg(rows){const x={consult:sum(rows,"c"),sales:sum(rows,"a"),converted:sum(rows,"t"),inquiryBase:sum(rows,"ib"),storeSalesBase:sum(rows,"sb"),shareSales:sum(rows,"sa"),shareDays:sum(rows,"sd"),days:sum(rows,"d"),fw:sum(rows,"fw"),fn:sum(rows,"fn"),aw:sum(rows,"aw"),an:sum(rows,"an")};x.conversion=x.inquiryBase?x.converted/x.inquiryBase*100:NaN;x.salesShareCoverage=x.days?x.shareDays/x.days*100:0;x.salesShare=x.storeSalesBase&&x.salesShareCoverage>=90?x.shareSales/x.storeSalesBase*100:NaN;x.salesPerConsult=x.consult?x.sales/x.consult:NaN;x.first=x.fn?x.fw/x.fn:NaN;x.avg=x.an?x.aw/x.an:NaN;return x;}
  function afterAgg(A,period){const issues=A.issuesWeek.filter(r=>r.period===period),sales=A.salesWeek.filter(r=>r.period===period),comp=A.compWeek.filter(r=>r.period===period),count=sum(issues,"count"),salesAmount=sum(sales,"amount"),paid=sum(comp,"paidAmount"),amount=sum(comp,"amount");return {issues,sales,comp,count,salesAmount,rate:salesAmount>0?count/salesAmount*10000:NaN,paid,amount,compCount:sum(comp,"count")};}
  function periodRange(period){const [year,w]=period.split("-W").map(Number),jan4=new Date(Date.UTC(year,0,4)),day=jan4.getUTCDay()||7,monday=new Date(jan4);monday.setUTCDate(jan4.getUTCDate()-day+1+(w-1)*7);const sunday=new Date(monday);sunday.setUTCDate(monday.getUTCDate()+6);const f=d=>`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`;return [f(monday),f(sunday)];}
  const lastYearPeriod=p=>`${Number(p.slice(0,4))-1}${p.slice(4)}`;
  function table(headers,rows,min="980px"){return `<div class="table-wrap"><table style="min-width:${min}"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`;}
  function trend(periods,values,formatter){return `<span class="mini-trend">${periods.map((p,i)=>`${p.slice(-3)} ${formatter(values[i])}`).join(" → ")}</span>`;}
  function reviewCard(label,value,current,previous,yoy,trendHtml,mode="pct",note="",kind="",metric=""){const mom=mode==="pp"?pp(current-previous):pct(change(current,previous)),year=Number.isFinite(yoy)?(mode==="pp"?pp(current-yoy):pct(change(current,yoy))):"—";return `<article class="review-kpi review-drill-value" ${drillAttrs(kind,metric)}><span>${label}</span><strong>${value}</strong><div class="review-comp"><b class="${cls(mode==="pp"?current-previous:change(current,previous))}">环比 ${mom}</b><b>同比 ${year}</b></div>${trendHtml}<small>${note} · 点击查看近4周</small></article>`;}

  function platformTable(P,periods,current,previous){const platforms=P.meta.platforms,curRows=P.week.filter(r=>r.p===current),prevRows=P.week.filter(r=>r.p===previous);const rows=platforms.map(name=>{const c=preAgg(curRows.filter(r=>r.pf===name)),p=preAgg(prevRows.filter(r=>r.pf===name)),ts=periods.map(x=>preAgg(P.week.filter(r=>r.p===x&&r.pf===name)).conversion);return {name,c,p,ts};}).sort((a,b)=>b.c.sales-a.c.sales);return table(["平台","咨询人数","环比","询单转化率","环比","客服净销售额","环比","平均响应","环比","近4周转化趋势"],rows.map((x,i)=>`<tr><td><span class="rank">${i+1}</span>${safe(x.name)}</td>${drillCell(fmt.format(x.c.consult),"prePlatform","consult",x.name)}${drillCell(pct(change(x.c.consult,x.p.consult)),"prePlatform","consult",x.name,"",cls(change(x.c.consult,x.p.consult)))}${drillCell(Number.isFinite(x.c.conversion)?x.c.conversion.toFixed(1)+"%":"—","prePlatform","conversion",x.name)}${drillCell(pp(x.c.conversion-x.p.conversion),"prePlatform","conversion",x.name,"",cls(x.c.conversion-x.p.conversion))}${drillCell(money(x.c.sales),"prePlatform","sales",x.name)}${drillCell(pct(change(x.c.sales,x.p.sales)),"prePlatform","sales",x.name,"",cls(change(x.c.sales,x.p.sales)))}${drillCell(Number.isFinite(x.c.avg)?x.c.avg.toFixed(1)+"秒":"—","prePlatform","avg",x.name)}${drillCell(pct(change(x.c.avg,x.p.avg)),"prePlatform","avg",x.name,"",cls(change(x.c.avg,x.p.avg)))}${drillCell(trend(periods,x.ts,v=>Number.isFinite(v)?v.toFixed(1)+"%":"—"),"prePlatform","conversion",x.name)}</tr>`),"1380px");}

  function issueTable(A,periods,current,previous){const cur=A.issuesWeek.filter(r=>r.period===current),prev=A.issuesWeek.filter(r=>r.period===previous),curTotal=sum(cur,"count"),prevTotal=sum(prev,"count"),salesNow=sum(A.salesWeek.filter(r=>r.period===current),"amount"),salesPrev=sum(A.salesWeek.filter(r=>r.period===previous),"amount"),names=[...new Set(cur.map(r=>r.issue))];const groupCount=(rows,name)=>sum(rows.filter(r=>r.issue===name),"count"),rankDimension=(rows,key)=>{const map=new Map();rows.forEach(r=>map.set(r[key]||"未分类",(map.get(r[key]||"未分类")||0)+Number(r.count||0)));return [...map].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count)},rankCategory=rows=>{const map=new Map();rows.forEach(r=>{const key=`${r.cat1||"未分类"}|§${r.cat2||"未分类"}`;map.set(key,(map.get(key)||0)+Number(r.count||0));});return [...map].map(([key,count])=>{const [cat1,cat2]=key.split("|§");return {cat1,cat2,name:cat2,count};}).sort((a,b)=>b.count-a.count)};const rows=names.map(name=>{const issueRows=cur.filter(r=>r.issue===name),count=groupCount(cur,name),last=groupCount(prev,name),share=curTotal?count/curTotal*100:NaN,lastShare=prevTotal?last/prevTotal*100:NaN,rate=salesNow?count/salesNow*10000:NaN,lastRate=salesPrev?last/salesPrev*10000:NaN,ts=periods.map(p=>groupCount(A.issuesWeek.filter(r=>r.period===p),name)),category=rankCategory(issueRows)[0]||{cat1:"—",cat2:"—",name:"—",count:0},productRows=issueRows.filter(r=>(r.cat1||"未分类")===category.cat1&&(r.cat2||"未分类")===category.cat2),product=rankDimension(productRows,"product")[0]||{name:"—",count:0};return {name,count,last,share,lastShare,rate,lastRate,ts,category,product};}).sort((a,b)=>b.count-a.count).slice(0,10);return table(["具体问题","本周起数","环比","占比（较上周）","每万元起数","环比","主要二级品类","该品类主要商品","近4周趋势"],rows.map((x,i)=>`<tr><td><span class="rank">${i+1}</span>${safe(x.name)}</td>${drillCell(fmt.format(x.count),"issue","count",x.name)}${drillCell(pct(change(x.count,x.last)),"issue","count",x.name,"",cls(change(x.count,x.last)))}${drillCell(`${x.share.toFixed(1)}% <small>(${pp(x.share-x.lastShare)})</small>`,"issue","share",x.name)}${drillCell(Number.isFinite(x.rate)?x.rate.toFixed(3):"—","issue","rate",x.name)}${drillCell(pct(change(x.rate,x.lastRate)),"issue","rate",x.name,"",cls(change(x.rate,x.lastRate)))}<td><b>${safe(x.category.name)}</b><br><small>${fmt.format(x.category.count)} 起 / ${(x.category.count/Math.max(1,x.count)*100).toFixed(1)}%</small></td><td>${safe(x.product.name)}<br><small>${fmt.format(x.product.count)} 起 / ${(x.product.count/Math.max(1,x.count)*100).toFixed(1)}%</small></td>${drillCell(trend(periods,x.ts,v=>fmt.format(v)),"issue","count",x.name)}</tr>`),"1560px");}

  function complaintPeriods(C){const rows=(C?.weeks||[]).filter(r=>r[0]<=C.meta.latestCompleteWeek),index=rows.findIndex(r=>r[0]===C.meta.latestCompleteWeek);return rows.slice(Math.max(0,index-3),index+1);}
  function complaintReview(C){if(!C)return `<section class="card review-section"><div class="empty">投诉复盘数据未加载</div></section>`;const periods=complaintPeriods(C),cur=periods.at(-1)||[],prev=periods.at(-2)||[],total=Number(cur[1]||0),previousTotal=Number(prev[1]||0),rows=C.types.map((name,i)=>{const count=Number(cur[2+i]||0),last=Number(prev[2+i]||0);return{name,count,last,share:total?count/total*100:NaN,trend:periods.map(r=>Number(r[2+i]||0))};}).filter(r=>r.count||r.last).sort((a,b)=>b.count-a.count);return `<section class="card review-section"><div class="section-head"><div><span class="section-index">${safe(C.meta.latestCompleteWeek)} · 投诉最新完整周</span><h2>投诉分析</h2><p class="subtitle">同时检查投诉量、类型占比、环比和近4周趋势；类型为规则初分</p></div><button class="back" data-workspace="complaint">查看投诉下钻 ›</button></div><div class="pre-conclusion"><strong>本周结论</strong><span>${safe(C.meta.latestCompleteWeek)} 投诉 ${total} 起，环比 ${pct(change(total,previousTotal))}。</span><em>${periods.map(r=>`${r[0].slice(-3)} ${r[1]}起`).join(" → ")}</em></div>${table(["投诉类型","本周起数","占比","环比","近4周趋势"],rows.map((r,i)=>`<tr><td><span class="rank">${i+1}</span>${safe(r.name)}</td><td>${r.count}</td><td>${Number.isFinite(r.share)?r.share.toFixed(1)+"%":"—"}</td><td class="${cls(change(r.count,r.last))}">${pct(change(r.count,r.last))}</td><td>${trend(periods.map(x=>x[0]),r.trend,v=>fmt.format(v))}</td></tr>`),"980px")}<div class="muted-box">平台与店铺是飞书关联字段；当前导出覆盖 ${C.meta.recordCount?((C.meta.storeExported||0)/C.meta.recordCount*100).toFixed(1):"0.0"}%，未达90%前不发布分渠道结论。</div></section>`;}

  function compensationTable(A,periods,current,previous){const currentRows=A.compWeek.filter(r=>r.period===current),previousRows=A.compWeek.filter(r=>r.period===previous),names=[...new Set(currentRows.map(r=>`${r.code||""}|§${r.product||"未填写产品"}`))];const stats=(period,key)=>{const rows=A.compWeek.filter(r=>r.period===period&&`${r.code||""}|§${r.product||"未填写产品"}`===key);return {paid:sum(rows,"paidAmount"),amount:sum(rows,"amount"),count:sum(rows,"count"),max:Math.max(0,...rows.map(r=>Number(r.maxSingle||0)))};};const rows=names.map(key=>{const [code,name]=key.split("|§"),c=stats(current,key),p=stats(previous,key),ts=periods.map(x=>stats(x,key).paid);return {code,name,c,p,ts};}).sort((a,b)=>(b.c.paid||b.c.amount)-(a.c.paid||a.c.amount)).slice(0,10);return table(["产品 / 编码","本周已打款","环比","登记金额","环比","记录数","环比","最大单笔（较上周）","近4周实付趋势"],rows.map((x,i)=>`<tr><td><span class="rank">${i+1}</span>${safe(x.name)}<br><small>${safe(x.code||"无编码")}</small></td>${drillCell(money(x.c.paid),"comp","paid",x.name,x.code)}${drillCell(pct(change(x.c.paid,x.p.paid)),"comp","paid",x.name,x.code,cls(change(x.c.paid,x.p.paid)))}${drillCell(money(x.c.amount),"comp","amount",x.name,x.code)}${drillCell(pct(change(x.c.amount,x.p.amount)),"comp","amount",x.name,x.code,cls(change(x.c.amount,x.p.amount)))}${drillCell(fmt.format(x.c.count),"comp","count",x.name,x.code)}${drillCell(pct(change(x.c.count,x.p.count)),"comp","count",x.name,x.code,cls(change(x.c.count,x.p.count)))}${drillCell(`${money(x.c.max)} <small>/ ${money(x.p.max)}</small>`,"comp","max",x.name,x.code)}${drillCell(trend(periods,x.ts,v=>money(v)),"comp","paid",x.name,x.code)}</tr>`),"1450px");}

  function returnAgg(row){if(!row)return {rq:0,sq:0,ra:0,sa:0,quantityRate:NaN,amountRate:NaN};const x={rq:Number(row[1]||0),sq:Number(row[2]||0),ra:Number(row[3]||0),sa:Number(row[4]||0)};x.quantityRate=x.sq?x.rq/x.sq*100:NaN;x.amountRate=x.sa?x.ra/x.sa*100:NaN;return x;}
  function returnRefundReview(R){
    if(!R)return `<section class="card review-section"><div class="empty">退货退款复盘数据未加载</div></section>`;
    const all=R.weekTotals.map(row=>row[0]),anomalies=R.meta.anomalyWeeks||[],latestMature=R.meta.latestMatureWeek||R.meta.latestWeek,eligible=all.filter(period=>period<=latestMature&&!anomalies.includes(period)),current=eligible.at(-1),index=eligible.indexOf(current),previous=eligible[index-1],periods=eligible.slice(Math.max(0,index-3),index+1),currentTotal=returnAgg(R.weekTotals.find(row=>row[0]===current)),previousTotal=returnAgg(R.weekTotals.find(row=>row[0]===previous));
    const category=(period)=>{const rows=R.categoryWeek.filter(row=>row[0]===period),map=new Map();rows.forEach(row=>{const key=`${row[1]}|§${row[2]}`,value=map.get(key)||[0,0,0,0];for(let i=0;i<4;i++)value[i]+=Number(row[i+3]||0);map.set(key,value);});return map;},currentMap=category(current),previousMap=category(previous),periodMaps=periods.map(category),minimumQuantity=Math.max(20,currentTotal.sq*.0005);
    const allRows=[...currentMap].map(([key,value])=>{const [cat1,cat2]=key.split("|§"),c=returnAgg(["",...value]),pRaw=previousMap.get(key),p=pRaw?returnAgg(["",...pRaw]):null,ts=periodMaps.map(map=>{const raw=map.get(key);return raw?returnAgg(["",...raw]):returnAgg(null);}),score=(Number.isFinite(c.quantityRate)&&currentTotal.quantityRate?c.quantityRate/currentTotal.quantityRate:0)+(Number.isFinite(c.amountRate)&&currentTotal.amountRate?c.amountRate/currentTotal.amountRate:0);return {key,cat1,cat2,c,p,ts,score};}).filter(x=>x.c.sq>=minimumQuantity);
    const lead=allRows.slice().sort((a,b)=>b.score-a.score).find(item=>!["物料","待匹配"].includes(item.cat1)&&item.cat2!=="待匹配")||allRows[0],conclusion=lead?`${lead.cat1} › ${lead.cat2} 的双指标综合风险最高：按数量 ${lead.c.quantityRate.toFixed(2)}%，按金额 ${lead.c.amountRate.toFixed(2)}%。本周建议下钻 SKU 核对主要退货对象。`:"本周未形成稳定品类异常信号。";
    const rows=allRows.slice().sort((a,b)=>{const value=item=>returnReviewSort.key==="quantityRate"?item.c.quantityRate:returnReviewSort.key==="amountRate"?item.c.amountRate:returnReviewSort.key==="shipQty"?item.c.sq:item.score;return (returnReviewSort.direction==="desc"?-1:1)*(value(a)-value(b));}).slice(0,8);
    const cards=`<div class="return-review-kpis"><article><span>发货退货退款率（按数量）</span><strong>${Number.isFinite(currentTotal.quantityRate)?currentTotal.quantityRate.toFixed(2)+"%":"—"}</strong><b class="${cls(currentTotal.quantityRate-previousTotal.quantityRate)}">环比 ${pp(currentTotal.quantityRate-previousTotal.quantityRate)}</b><small>${trend(periods,periods.map(p=>returnAgg(R.weekTotals.find(row=>row[0]===p)).quantityRate),v=>Number.isFinite(v)?v.toFixed(2)+"%":"—")}</small></article><article><span>发货退货退款率（按金额）</span><strong>${Number.isFinite(currentTotal.amountRate)?currentTotal.amountRate.toFixed(2)+"%":"—"}</strong><b class="${cls(currentTotal.amountRate-previousTotal.amountRate)}">环比 ${pp(currentTotal.amountRate-previousTotal.amountRate)}</b><small>${trend(periods,periods.map(p=>returnAgg(R.weekTotals.find(row=>row[0]===p)).amountRate),v=>Number.isFinite(v)?v.toFixed(2)+"%":"—")}</small></article></div>`;
    const sortHead=(key,label)=>`<button type="button" class="review-sort-button ${returnReviewSort.key===key?"active":""}" data-return-review-sort="${key}">${label}<span>${returnReviewSort.key===key?(returnReviewSort.direction==="desc"?"↓":"↑"):"↕"}</span></button>`;
    const ranking=table(["一级大类 › 二级品类",sortHead("quantityRate","按数量退款率"),"环比",sortHead("amountRate","按金额退款率"),"环比",sortHead("shipQty","实发数量"),"近4个成熟周双指标趋势"],rows.map((x,i)=>`<tr><td><span class="rank">${i+1}</span>${safe(x.cat1)}<br><strong>${safe(x.cat2)}</strong></td><td>${Number.isFinite(x.c.quantityRate)?x.c.quantityRate.toFixed(2)+"%":"—"}</td><td class="${cls(x.p?x.c.quantityRate-x.p.quantityRate:NaN)}">${x.p?pp(x.c.quantityRate-x.p.quantityRate):"—"}</td><td>${Number.isFinite(x.c.amountRate)?x.c.amountRate.toFixed(2)+"%":"—"}</td><td class="${cls(x.p?x.c.amountRate-x.p.amountRate:NaN)}">${x.p?pp(x.c.amountRate-x.p.amountRate):"—"}</td><td>${fmt.format(x.c.sq)}</td><td><small>${x.ts.map((v,ti)=>`${periods[ti].slice(-3)} ${Number.isFinite(v.quantityRate)?v.quantityRate.toFixed(1)+"%":"—"}/${Number.isFinite(v.amountRate)?v.amountRate.toFixed(1)+"%":"—"}`).join(" → ")}</small></td></tr>`),"1360px");
    return `<section class="card review-section return-review-section"><div class="section-head"><div><span class="section-index">${safe(current)} · 15天成熟周</span><h2>退货退款复盘</h2><p class="subtitle">只看发货后退货退款，按数量与按金额两个口径同时判断；点击表头可切换升降序</p></div><button class="back" data-workspace="returns">查看完整退货退款分析 ›</button></div>${cards}<div class="pre-conclusion return-conclusion"><strong>本周结论</strong><span>${safe(conclusion)}</span><em>退货数据截至 ${safe(R.meta.sourceMax)}</em></div>${ranking}<div class="muted-box">按数量 = 实退数量 ÷ 实发数量；按金额 = 实退金额 ÷ 实发金额。复盘仅使用满足 ${R.meta.maturityDays||15} 天观察窗的退货周，当前截止 ${safe(current)}。${anomalies.length?`源表 ${safe(anomalies.join("、"))} 全盘指标异常偏低，已排除正式结论。`:""}</div></section>`;
  }

  const metricSpecs = {
    consult:{label:"咨询人数",format:v=>fmt.format(v),mode:"pct"},
    conversion:{label:"询单转化率",format:v=>Number.isFinite(v)?`${v.toFixed(1)}%`:"—",mode:"pp"},
    sales:{label:"客服净销售额",format:money,mode:"pct"},
    avg:{label:"平均响应",format:v=>Number.isFinite(v)?`${v.toFixed(1)}秒`:"—",mode:"pct"},
    count:{label:"售后起数",format:v=>fmt.format(v),mode:"pct"},
    rate:{label:"每万元售后起数",format:v=>Number.isFinite(v)?v.toFixed(3):"—",mode:"pct"},
    share:{label:"售后起数占比",format:v=>Number.isFinite(v)?`${v.toFixed(1)}%`:"—",mode:"pp"},
    paid:{label:"实际已打款",format:money,mode:"pct"},
    amount:{label:"登记赔偿金额",format:money,mode:"pct"},
    max:{label:"最大单笔",format:money,mode:"pct"}
  };

  function reviewMetricValue(kind,metric,period,name="",code=""){
    const P=window.PRE_SALES_DATA,A=window.AFTER_SALES_DATA;
    if(kind==="preTotal"||kind==="prePlatform"){
      const rows=P.week.filter(r=>r.p===period&&(kind==="preTotal"||r.pf===name));
      return preAgg(rows)[metric];
    }
    if(kind==="afterTotal") return afterAgg(A,period)[metric];
    if(kind==="issue"){
      const rows=A.issuesWeek.filter(r=>r.period===period),count=sum(rows.filter(r=>r.issue===name),"count"),total=sum(rows,"count"),sales=sum(A.salesWeek.filter(r=>r.period===period),"amount");
      if(metric==="share")return total?count/total*100:NaN;
      if(metric==="rate")return sales?count/sales*10000:NaN;
      return count;
    }
    if(kind==="comp"){
      const rows=A.compWeek.filter(r=>r.period===period&&r.product===name&&String(r.code||"")===String(code||""));
      if(metric==="max")return Math.max(0,...rows.map(r=>Number(r.maxSingle||0)));
      return sum(rows,metric==="paid"?"paidAmount":metric);
    }
    return NaN;
  }

  function reviewTrendSvg(periods,values,spec){
    const finite=values.filter(Number.isFinite);if(!finite.length)return `<div class="empty">最近4周没有可用数据</div>`;
    const W=900,H=260,L=55,R=30,T=45,B=52,iw=W-L-R,ih=H-T-B,min=Math.min(0,...finite),max=Math.max(1,...finite),span=Math.max(1,max-min),x=i=>L+(periods.length===1?iw/2:i*iw/(periods.length-1)),y=v=>T+ih-(v-min)/span*ih,path=values.map((v,i)=>Number.isFinite(v)?`${i===0||!Number.isFinite(values[i-1])?"M":"L"}${x(i)},${y(v)}`:"").join(" ");
    let svg=`<svg class="modal-trend-svg" viewBox="0 0 ${W} ${H}"><line x1="${L}" y1="${T+ih}" x2="${W-R}" y2="${T+ih}" stroke="var(--line)"/><path d="${path}" fill="none" stroke="var(--red)" stroke-width="4"/>`;
    periods.forEach((p,i)=>{const v=values[i];svg+=`<text x="${x(i)}" y="${H-16}" text-anchor="middle" fill="var(--muted)" font-size="13">${safe(p)}</text>`;if(Number.isFinite(v))svg+=`<circle cx="${x(i)}" cy="${y(v)}" r="6" fill="var(--panel)" stroke="var(--red)" stroke-width="4"/><text x="${x(i)}" y="${Math.max(18,y(v)-13)}" text-anchor="middle" fill="var(--red)" font-size="13" font-weight="800">${safe(spec.format(v))}</text>`;});
    return svg+`</svg>`;
  }

  function openReviewDrill(target){
    const kind=target.dataset.reviewKind,metric=target.dataset.reviewMetric,name=target.dataset.reviewName||"",code=target.dataset.reviewCode||"",spec=metricSpecs[metric];
    if(!spec||!window.DASHBOARD_MODAL)return;
    const context=kind.startsWith("pre")?reviewContext.pre:reviewContext.after,periods=context.periods,values=periods.map(p=>reviewMetricValue(kind,metric,p,name,code)),rows=periods.map((p,i)=>{
      const commonIndex=context.common.indexOf(p),previous=commonIndex>0?context.common[commonIndex-1]:"",prev=previous?reviewMetricValue(kind,metric,previous,name,code):NaN,yoy=reviewMetricValue(kind,metric,lastYearPeriod(p),name,code),mom=spec.mode==="pp"?pp(values[i]-prev):pct(change(values[i],prev)),year=spec.mode==="pp"?pp(values[i]-yoy):pct(change(values[i],yoy));
      return `<tr><td>${safe(p)}</td><td>${safe(spec.format(values[i]))}</td><td class="${cls(spec.mode==="pp"?values[i]-prev:change(values[i],prev))}">${mom}</td><td>${year}</td></tr>`;
    }),finite=periods.map((p,i)=>({p,v:values[i]})).filter(x=>Number.isFinite(x.v)),high=finite.slice().sort((a,b)=>b.v-a.v)[0],low=finite.slice().sort((a,b)=>a.v-b.v)[0],scope=name?`${name}${code?` / ${code}`:""}`:"全部范围";
    window.DASHBOARD_MODAL.open({title:`${scope} · ${spec.label}`,subtitle:`最近4个完整销售周 · 点击遮罩、右上角 × 或按 Esc 关闭`,html:`<div class="modal-summary"><span>最高周 <b>${high?safe(high.p)+" · "+safe(spec.format(high.v)):"—"}</b></span><span>最低周 <b>${low?safe(low.p)+" · "+safe(spec.format(low.v)):"—"}</b></span></div>${reviewTrendSvg(periods,values,spec)}${table(["周次","当周数值","环比","同比"],rows,"680px")}`});
  }

  const byCount=(rows,key)=>{const map=new Map();rows.forEach(r=>{const name=key(r);map.set(name,(map.get(name)||0)+Number(r.count||0));});return [...map].sort((a,b)=>b[1]-a[1]);};
  function dueDate(C){const raw=C?.meta?.generatedAt?.slice(0,10)||new Date().toISOString().slice(0,10),d=new Date(`${raw}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+7);return d.toISOString().slice(0,10);}
  function returnRisk(R){if(!R)return null;const current=R.meta.latestMatureWeek,all=R.weekTotals.map(r=>r[0]),index=all.indexOf(current),previous=all[index-1],tot=returnAgg(R.weekTotals.find(r=>r[0]===current)),mapFor=p=>{const m=new Map();R.categoryWeek.filter(r=>r[0]===p).forEach(r=>{const key=`${r[1]}|§${r[2]}`,v=m.get(key)||[0,0,0,0];for(let i=0;i<4;i++)v[i]+=Number(r[i+3]||0);m.set(key,v);});return m;},cur=mapFor(current),prev=mapFor(previous),rows=[...cur].map(([key,v])=>{const [cat1,cat2]=key.split("|§"),c=returnAgg(["",...v]),p=prev.has(key)?returnAgg(["",...prev.get(key)]):null,score=(Number.isFinite(c.quantityRate)&&tot.quantityRate?c.quantityRate/tot.quantityRate:0)+(Number.isFinite(c.amountRate)&&tot.amountRate?c.amountRate/tot.amountRate:0);return{cat1,cat2,c,p,score};}).filter(x=>x.c.sq>=Math.max(20,tot.sq*.0005)&&!["物料","待匹配"].includes(x.cat1)&&x.cat2!=="待匹配").sort((a,b)=>b.score-a.score);return rows[0]?{...rows[0],current,previous}:null;}
  function actionRows(P,A,C,R,preCurrent,prePrevious,afterCurrent,afterPrevious){const actions=[],due=dueDate(C),preRows=P.week.filter(r=>r.p===preCurrent),shops=[...new Set(preRows.map(r=>r.s))].map(shop=>{const row=preRows.find(r=>r.s===shop),c=preAgg(preRows.filter(r=>r.s===shop)),p=preAgg(P.week.filter(r=>r.p===prePrevious&&r.s===shop));return{platform:row?.pf||"—",shop,c,p,delta:c.conversion-p.conversion};}).sort((a,b)=>a.delta-b.delta),weak=shops.find(x=>Number.isFinite(x.delta)&&x.delta<0);
    if(weak)actions.push({level:Math.abs(weak.delta)>=3?"P0":"P1",module:"售前经营",platform:weak.platform,shop:weak.shop,cat1:"不适用",cat2:"不适用",product:"未成交咨询样本",code:"不适用",problem:"询单转化率下降",evidence:`${preCurrent} ${weak.c.conversion.toFixed(1)}%，环比 ${pp(weak.delta)}；咨询 ${fmt.format(weak.c.consult)}人，环比 ${pct(change(weak.c.consult,weak.p.consult))}`,team:"店铺客服、平台运营",action:"抽样未成交咨询，分开标注流量、价格权益、商品与话术原因",due,check:"询单转化率至少回到近4周均值，并提供未成交原因分布"});
    shops.filter(x=>x.c.days&&x.c.salesShareCoverage<90).forEach(x=>actions.push({level:"P1",module:"售前数据质量",platform:x.platform,shop:x.shop,cat1:"不适用",cat2:"不适用",product:"客服销售占比",code:"不适用",problem:"销售占比同日有效完整率不足",evidence:`${preCurrent} ${x.c.shareDays||0}/${x.c.days}天有效，完整率 ${x.c.salesShareCoverage.toFixed(1)}%，看板显示“—”`,team:"数据填报、店铺客服",action:"按日补齐客服销售额与店铺销售分母，不用整周总额反推",due,check:"分子分母同日有效率达90%以上"}));
    const cur=A.issuesWeek.filter(r=>r.period===afterCurrent),prev=A.issuesWeek.filter(r=>r.period===afterPrevious),risks=[...new Set(cur.map(r=>r.issue))].map(name=>{const count=sum(cur.filter(r=>r.issue===name),"count"),last=sum(prev.filter(r=>r.issue===name),"count");return{name,count,last,delta:count-last,rate:change(count,last)};}).sort((a,b)=>b.delta-a.delta),risk=risks[0];if(risk&&risk.delta>0){const issueRows=cur.filter(r=>r.issue===risk.name),atomic=byCount(issueRows,r=>[r.platform,r.shop,r.cat1,r.cat2,r.product,r.code].join("|§"))[0],parts=atomic?.[0].split("|§")||[],atomicLast=sum(prev.filter(r=>r.issue===risk.name&&[r.platform,r.shop,r.cat1,r.cat2,r.product,r.code].join("|§")===atomic?.[0]),"count");actions.push({level:risk.rate>=30&&risk.delta>=10?"P0":"P1",module:"售后分析",platform:parts[0]||"—",shop:parts[1]||"—",cat1:parts[2]||"—",cat2:parts[3]||"—",product:parts[4]||"—",code:parts[5]||"—",problem:`${risk.name}售后起数上升`,evidence:`${afterCurrent}全部 ${risk.count}起，较上周 +${risk.delta}起（${pct(risk.rate)}）；该精确对象 ${atomic?.[1]||0}起，较上周 ${atomicLast?`${pct(change(atomic?.[1]||0,atomicLast))}`:`+${atomic?.[1]||0}起（基期为0）`}`,team:"产品、店铺运营、客服、品控",action:"核对该编码批次和施工场景，抽检同编码记录并形成预防话术/作业指引",due,check:"该编码同问题起数环比下降，且售后每万元起数不上升"});}
    if(C){const periods=complaintPeriods(C),cc=periods.at(-1)||[],cp=periods.at(-2)||[],types=C.types.map((name,i)=>({name,count:Number(cc[2+i]||0),last:Number(cp[2+i]||0)})).map(x=>({...x,delta:x.count-x.last})).sort((a,b)=>b.delta-a.delta),top=types[0],[cs,ce]=periodRange(C.meta.latestCompleteWeek),affected=(C.recentDetails||[]).filter(r=>r[0]>=cs&&r[0]<=ce&&r[2]===top.name).map(r=>r[1]),products=[...new Set(affected)];if(top&&top.delta>0)actions.push({level:top.delta>=3?"P1":"P2",module:"投诉分析",platform:"关联字段权限待开放",shop:"关联字段权限待开放",cat1:"源表未提供",cat2:top.name,product:products.join("、")||"产品字段缺失",code:"源表未提供",problem:`${top.name}投诉上升`,evidence:`${C.meta.latestCompleteWeek} ${top.count}起，较上周 +${top.delta}起；影响 ${products.length}个已填写产品；平台/店铺覆盖 0.0%`,team:"客服、产品、运营、数据管理",action:"逐个产品下钻复核脱敏问题标签；同时开放关联店铺字段以追到渠道",due,check:"同类投诉不高于本周；处理结果完成填写；店铺字段覆盖率达90%"});}
    const rr=returnRisk(R);if(rr)actions.push({level:"P1",module:"退货退款",platform:"摘要源未提供",shop:"摘要源未提供",cat1:rr.cat1,cat2:rr.cat2,product:"请在退货退款页继续下钻SKU",code:"摘要源未提供",problem:"发货退货退款双指标风险偏高",evidence:`${rr.current}按数量 ${rr.c.quantityRate.toFixed(2)}%、按金额 ${rr.c.amountRate.toFixed(2)}%；环比 ${rr.p?`${pp(rr.c.quantityRate-rr.p.quantityRate)} / ${pp(rr.c.amountRate-rr.p.amountRate)}`:"基期缺失"}`,team:"品类运营、仓储、产品、客服",action:"进入退货退款页按二级品类下钻SKU，区分质量、发错、破损和非商品原因",due,check:"按数量与按金额退款率均环比下降，并形成TOP SKU及原因占比"});return actions;}
  function actionObject(x){return `<b>平台：</b>${safe(x.platform)}<br><b>店铺：</b>${safe(x.shop)}<br><b>一级/二级：</b>${safe(x.cat1)} › ${safe(x.cat2)}<br><b>商品/编码：</b>${safe(x.product)} / ${safe(x.code)}`;}

  function render(){const P=window.PRE_SALES_DATA,A=window.AFTER_SALES_DATA,C=window.COMPLAINT_DATA,root=$("#weeklyReviewBody");if(!root)return;if(!P||!A){root.innerHTML=`<article class="card loading-card"><div class="loading-dot"></div><h2>正在准备上周复盘…</h2></article>`;return;}
    const preSet=new Set(P.week.map(r=>r.p)),issueSet=new Set(A.issuesWeek.map(r=>r.period)),salesSet=new Set(A.salesWeek.filter(r=>Number(r.amount)>0).map(r=>r.period)),completeCutoff=[P.meta.commonComplete,A.meta.afterSalesMax,A.meta.salesMax].filter(Boolean).sort()[0],preCommon=[...preSet].filter(p=>issueSet.has(p)&&salesSet.has(p)&&(!completeCutoff||periodRange(p)[1]<=completeCutoff)).sort(),preCurrent=preCommon.at(-1),preIdx=preCommon.indexOf(preCurrent),prePrevious=preCommon[preIdx-1],prePeriods=preCommon.slice(Math.max(0,preIdx-3),preIdx+1),preYoyPeriod=lastYearPeriod(preCurrent),[start,end]=periodRange(preCurrent),curPre=preAgg(P.week.filter(r=>r.p===preCurrent)),prevPre=preAgg(P.week.filter(r=>r.p===prePrevious)),yoyPreRows=P.week.filter(r=>r.p===preYoyPeriod),yoyPre=yoyPreRows.length?preAgg(yoyPreRows):null;
    const afterCutoff=[A.meta.afterSalesMax,A.meta.salesMax].filter(Boolean).sort()[0],afterCommon=[...issueSet].filter(p=>salesSet.has(p)&&(!afterCutoff||periodRange(p)[1]<=afterCutoff)).sort(),afterCurrent=afterCommon.at(-1),afterIdx=afterCommon.indexOf(afterCurrent),afterPrevious=afterCommon[afterIdx-1],afterPeriods=afterCommon.slice(Math.max(0,afterIdx-3),afterIdx+1),afterYoyPeriod=lastYearPeriod(afterCurrent),curAfter=afterAgg(A,afterCurrent),prevAfter=afterAgg(A,afterPrevious),yoyAfterRows=A.issuesWeek.filter(r=>r.period===afterYoyPeriod),yoyAfter=yoyAfterRows.length?afterAgg(A,afterYoyPeriod):null,returnCurrent=window.RETURN_REFUND_SUMMARY?.meta?.latestMatureWeek||"—";
    reviewContext.pre={periods:prePeriods,common:preCommon,current:preCurrent};reviewContext.after={periods:afterPeriods,common:afterCommon,current:afterCurrent};
    const preByPeriod=p=>preAgg(P.week.filter(r=>r.p===p)),afterByPeriod=p=>afterAgg(A,p),preTrend=prePeriods.map(preByPeriod),afterTrend=afterPeriods.map(afterByPeriod),cards=[
      reviewCard("咨询人数",fmt.format(curPre.consult),curPre.consult,prevPre.consult,yoyPre?.consult,trend(prePeriods,preTrend.map(x=>x.consult),v=>fmt.format(v)),"pct",`${preCurrent} · 售前工作量`,"preTotal","consult"),
      reviewCard("询单转化率",Number.isFinite(curPre.conversion)?curPre.conversion.toFixed(1)+"%":"—",curPre.conversion,prevPre.conversion,yoyPre?.conversion,trend(prePeriods,preTrend.map(x=>x.conversion),v=>Number.isFinite(v)?v.toFixed(1)+"%":"—"),"pp",`${preCurrent} · 每日填报口径加权`,"preTotal","conversion"),
      reviewCard("客服净销售额",money(curPre.sales),curPre.sales,prevPre.sales,yoyPre?.sales,trend(prePeriods,preTrend.map(x=>x.sales),money),"pct",`${preCurrent} · 去退后销售额`,"preTotal","sales"),
      reviewCard("有效售后起数",fmt.format(curAfter.count),curAfter.count,prevAfter.count,yoyAfter?.count,trend(afterPeriods,afterTrend.map(x=>x.count),v=>fmt.format(v)),"pct",`${afterCurrent} · 一条有效登记计1起`,"afterTotal","count"),
      reviewCard("每万元售后起数",Number.isFinite(curAfter.rate)?curAfter.rate.toFixed(3):"—",curAfter.rate,prevAfter.rate,yoyAfter?.rate,trend(afterPeriods,afterTrend.map(x=>x.rate),v=>Number.isFinite(v)?v.toFixed(3):"—"),"pct",`${afterCurrent} · 售后起数 ÷ 电商销售额 × 10,000`,"afterTotal","rate"),
      C?`<article class="review-kpi review-drill-value" data-workspace="complaint"><span>投诉量</span><strong>${fmt.format(complaintPeriods(C).at(-1)?.[1]||0)}</strong><div class="review-comp"><b class="${cls(change(complaintPeriods(C).at(-1)?.[1]||0,complaintPeriods(C).at(-2)?.[1]||0))}">环比 ${pct(change(complaintPeriods(C).at(-1)?.[1]||0,complaintPeriods(C).at(-2)?.[1]||0))}</b><b>同比 基期缺失</b></div>${trend(complaintPeriods(C).map(r=>r[0]),complaintPeriods(C).map(r=>r[1]),v=>fmt.format(v))}<small>${C.meta.latestCompleteWeek} · 点击投诉分析查看下钻</small></article>`:""
    ].join("");
    const actions=actionRows(P,A,C,window.RETURN_REFUND_SUMMARY,preCurrent,prePrevious,afterCurrent,afterPrevious);
    root.innerHTML=`<section class="review-head panel"><div><span class="review-eyebrow">各模块最新可用周期</span><h2>客服售前售后复盘</h2><p>售前正式 ${preCurrent}（${start} 至 ${end}） · 售后完整 ${afterCurrent} · 投诉完整 ${C?.meta?.latestCompleteWeek||"—"} · 退货退款成熟 ${returnCurrent}</p></div><div class="review-actions"><button data-workspace="pre">查看售前明细</button><button data-workspace="after">查看售后明细</button><button data-workspace="complaint">查看投诉明细</button><button data-workspace="returns">查看退货退款明细</button></div></section><section class="review-kpis">${cards}</section><section class="card review-section"><div class="section-head"><div><span class="section-index">${preCurrent} · 售前最新完整周</span><h2>售前转化与服务效率</h2><p class="subtitle">每项同时展示本周值、环比和近4周趋势</p></div></div>${platformTable(P,prePeriods,preCurrent,prePrevious)}</section><section class="card review-section"><div class="section-head"><div><span class="section-index">${afterCurrent} · 售后最新完整周</span><h2>售后问题变化</h2><p class="subtitle">按本周售后起数降序，同时检查占比、每万元起数和连续趋势</p></div></div>${issueTable(A,afterPeriods,afterCurrent,afterPrevious)}</section>${complaintReview(C)}${returnRefundReview(window.RETURN_REFUND_SUMMARY)}<section class="card review-section action-card"><div class="section-head"><div><h2>本周协同改善清单</h2><p class="subtitle">覆盖售前、售后、投诉、退货退款与数据质量；整改对象落到源数据支持的最细颗粒</p></div></div>${table(["优先级","板块","整改对象","问题变化","数据证据","协同角色","本周动作","截止时间","下周验收"],actions.map(x=>`<tr><td><span class="tag ${x.level==="P0"?"red":"blue"}">${x.level}</span></td><td><b>${safe(x.module)}</b></td><td class="review-action-object">${actionObject(x)}</td><td><b>${safe(x.problem)}</b></td><td>${safe(x.evidence)}</td><td>${safe(x.team)}</td><td>${safe(x.action)}</td><td>${safe(x.due)}</td><td>${safe(x.check)}</td></tr>`),"2100px")}</section><div class="notice review-notice">正式售前复盘共同完整截止 ${completeCutoff||"—"}；售后按登记与销售分母共同完整至 ${afterCutoff||"—"}。数据截止：售前 ${P.meta.sourceMax}，售后 ${A.meta.afterSalesMax}，电商销售 ${A.meta.salesMax}，投诉 ${C?.meta?.sourceMax||"—"}，退货退款 ${window.RETURN_REFUND_SUMMARY?.meta?.sourceMax||"—"}。缺失平台、店铺或编码时明确标记“源表未提供/权限待开放”，不作猜测归因。</div>`;
  }
  document.addEventListener("click",event=>{const sort=event.target.closest("#weeklyReviewWorkspace [data-return-review-sort]");if(sort){const key=sort.dataset.returnReviewSort;if(returnReviewSort.key===key)returnReviewSort.direction=returnReviewSort.direction==="desc"?"asc":"desc";else{returnReviewSort.key=key;returnReviewSort.direction="desc";}render();return;}const target=event.target.closest("#weeklyReviewWorkspace [data-review-drill]");if(target)openReviewDrill(target);});
  window.WEEKLY_REVIEW_APP={render};
})();
