(() => {
  "use strict";
  const $ = s => document.querySelector(s);
  const fmt = new Intl.NumberFormat("zh-CN", {maximumFractionDigits:1});
  const money = n => `¥${fmt.format(Number(n || 0))}`;
  const safe = s => String(s ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const sum = (rows,key) => rows.reduce((a,r)=>a+Number(r[key]||0),0);
  const change = (a,b) => Number.isFinite(a)&&Number.isFinite(b)&&b!==0?(a/b-1)*100:NaN;
  const pct = n => Number.isFinite(n)?`${n>=0?"+":""}${n.toFixed(1)}%`:"—";
  const pp = n => Number.isFinite(n)?`${n>=0?"+":""}${n.toFixed(1)}pp`:"—";
  const cls = n => Number.isFinite(n)?(n>0?"up":"down"):"muted";

  function preAgg(rows){const x={consult:sum(rows,"c"),sales:sum(rows,"a"),converted:sum(rows,"t"),inquiryBase:sum(rows,"ib"),storeSalesBase:sum(rows,"sb"),shareSales:sum(rows,"sa"),shareDays:sum(rows,"sd"),days:sum(rows,"d"),fw:sum(rows,"fw"),fn:sum(rows,"fn"),aw:sum(rows,"aw"),an:sum(rows,"an")};x.conversion=x.inquiryBase?x.converted/x.inquiryBase*100:NaN;x.salesShareCoverage=x.days?x.shareDays/x.days*100:0;x.salesShare=x.storeSalesBase&&x.salesShareCoverage>=90?x.shareSales/x.storeSalesBase*100:NaN;x.salesPerConsult=x.consult?x.sales/x.consult:NaN;x.first=x.fn?x.fw/x.fn:NaN;x.avg=x.an?x.aw/x.an:NaN;return x;}
  function afterAgg(A,period){const issues=A.issuesWeek.filter(r=>r.period===period),sales=A.salesWeek.filter(r=>r.period===period),comp=A.compWeek.filter(r=>r.period===period),count=sum(issues,"count"),salesAmount=sum(sales,"amount"),paid=sum(comp,"paidAmount"),amount=sum(comp,"amount");return {issues,sales,comp,count,salesAmount,rate:salesAmount>0?count/salesAmount*10000:NaN,paid,amount,compCount:sum(comp,"count")};}
  function periodRange(period){const [year,w]=period.split("-W").map(Number),jan4=new Date(Date.UTC(year,0,4)),day=jan4.getUTCDay()||7,monday=new Date(jan4);monday.setUTCDate(jan4.getUTCDate()-day+1+(w-1)*7);const sunday=new Date(monday);sunday.setUTCDate(monday.getUTCDate()+6);const f=d=>`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`;return [f(monday),f(sunday)];}
  const lastYearPeriod=p=>`${Number(p.slice(0,4))-1}${p.slice(4)}`;
  function table(headers,rows,min="980px"){return `<div class="table-wrap"><table style="min-width:${min}"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`;}
  function trend(periods,values,formatter){return `<span class="mini-trend">${periods.map((p,i)=>`${p.slice(-3)} ${formatter(values[i])}`).join(" → ")}</span>`;}
  function reviewCard(label,value,current,previous,yoy,trendHtml,mode="pct",note=""){const mom=mode==="pp"?pp(current-previous):pct(change(current,previous)),year=Number.isFinite(yoy)?(mode==="pp"?pp(current-yoy):pct(change(current,yoy))):"—";return `<article class="review-kpi"><span>${label}</span><strong>${value}</strong><div class="review-comp"><b class="${cls(mode==="pp"?current-previous:change(current,previous))}">环比 ${mom}</b><b>同比 ${year}</b></div>${trendHtml}<small>${note}</small></article>`;}

  function platformTable(P,periods,current,previous){const platforms=P.meta.platforms,curRows=P.week.filter(r=>r.p===current),prevRows=P.week.filter(r=>r.p===previous);const rows=platforms.map(name=>{const c=preAgg(curRows.filter(r=>r.pf===name)),p=preAgg(prevRows.filter(r=>r.pf===name)),ts=periods.map(x=>preAgg(P.week.filter(r=>r.p===x&&r.pf===name)).conversion);return {name,c,p,ts};}).sort((a,b)=>b.c.sales-a.c.sales);return table(["平台","咨询人数","环比","询单转化率","环比","客服净销售额","环比","平均响应","环比","近4周转化趋势"],rows.map((x,i)=>`<tr><td><span class="rank">${i+1}</span>${safe(x.name)}</td><td>${fmt.format(x.c.consult)}</td><td class="${cls(change(x.c.consult,x.p.consult))}">${pct(change(x.c.consult,x.p.consult))}</td><td>${Number.isFinite(x.c.conversion)?x.c.conversion.toFixed(1)+"%":"—"}</td><td class="${cls(x.c.conversion-x.p.conversion)}">${pp(x.c.conversion-x.p.conversion)}</td><td>${money(x.c.sales)}</td><td class="${cls(change(x.c.sales,x.p.sales))}">${pct(change(x.c.sales,x.p.sales))}</td><td>${Number.isFinite(x.c.avg)?x.c.avg.toFixed(1)+"秒":"—"}</td><td class="${cls(change(x.c.avg,x.p.avg))}">${pct(change(x.c.avg,x.p.avg))}</td><td>${trend(periods,x.ts,v=>Number.isFinite(v)?v.toFixed(1)+"%":"—")}</td></tr>`),"1380px");}

  function issueTable(A,periods,current,previous){const cur=A.issuesWeek.filter(r=>r.period===current),prev=A.issuesWeek.filter(r=>r.period===previous),curTotal=sum(cur,"count"),prevTotal=sum(prev,"count"),salesNow=sum(A.salesWeek.filter(r=>r.period===current),"amount"),salesPrev=sum(A.salesWeek.filter(r=>r.period===previous),"amount"),names=[...new Set(cur.map(r=>r.issue))];const groupCount=(rows,name)=>sum(rows.filter(r=>r.issue===name),"count");const rows=names.map(name=>{const count=groupCount(cur,name),last=groupCount(prev,name),share=curTotal?count/curTotal*100:NaN,lastShare=prevTotal?last/prevTotal*100:NaN,rate=salesNow?count/salesNow*10000:NaN,lastRate=salesPrev?last/salesPrev*10000:NaN,ts=periods.map(p=>groupCount(A.issuesWeek.filter(r=>r.period===p),name)),products=[...new Map(cur.filter(r=>r.issue===name).map(r=>[r.product,{name:r.product,count:0}])).values()];products.forEach(x=>x.count=sum(cur.filter(r=>r.issue===name&&r.product===x.name),"count"));products.sort((a,b)=>b.count-a.count);return {name,count,last,share,lastShare,rate,lastRate,ts,product:products[0]?.name||"—"};}).sort((a,b)=>b.count-a.count).slice(0,10);return table(["具体问题","本周起数","环比","占比（较上周）","每万元起数","环比","主要涉及产品","近4周趋势"],rows.map((x,i)=>`<tr><td><span class="rank">${i+1}</span>${safe(x.name)}</td><td>${fmt.format(x.count)}</td><td class="${cls(change(x.count,x.last))}">${pct(change(x.count,x.last))}</td><td>${x.share.toFixed(1)}% <small>(${pp(x.share-x.lastShare)})</small></td><td>${Number.isFinite(x.rate)?x.rate.toFixed(3):"—"}</td><td class="${cls(change(x.rate,x.lastRate))}">${pct(change(x.rate,x.lastRate))}</td><td>${safe(x.product)}</td><td>${trend(periods,x.ts,v=>fmt.format(v))}</td></tr>`),"1380px");}

  function compensationTable(A,periods,current,previous){const currentRows=A.compWeek.filter(r=>r.period===current),previousRows=A.compWeek.filter(r=>r.period===previous),names=[...new Set(currentRows.map(r=>`${r.code||""}|§${r.product||"未填写产品"}`))];const stats=(period,key)=>{const rows=A.compWeek.filter(r=>r.period===period&&`${r.code||""}|§${r.product||"未填写产品"}`===key);return {paid:sum(rows,"paidAmount"),amount:sum(rows,"amount"),count:sum(rows,"count"),max:Math.max(0,...rows.map(r=>Number(r.maxSingle||0)))};};const rows=names.map(key=>{const [code,name]=key.split("|§"),c=stats(current,key),p=stats(previous,key),ts=periods.map(x=>stats(x,key).paid);return {code,name,c,p,ts};}).sort((a,b)=>(b.c.paid||b.c.amount)-(a.c.paid||a.c.amount)).slice(0,10);return table(["产品 / 编码","本周已打款","环比","登记金额","环比","记录数","环比","最大单笔（较上周）","近4周实付趋势"],rows.map((x,i)=>`<tr><td><span class="rank">${i+1}</span>${safe(x.name)}<br><small>${safe(x.code||"无编码")}</small></td><td>${money(x.c.paid)}</td><td class="${cls(change(x.c.paid,x.p.paid))}">${pct(change(x.c.paid,x.p.paid))}</td><td>${money(x.c.amount)}</td><td class="${cls(change(x.c.amount,x.p.amount))}">${pct(change(x.c.amount,x.p.amount))}</td><td>${fmt.format(x.c.count)}</td><td class="${cls(change(x.c.count,x.p.count))}">${pct(change(x.c.count,x.p.count))}</td><td>${money(x.c.max)} <small>/ ${money(x.p.max)}</small></td><td>${trend(periods,x.ts,v=>money(v))}</td></tr>`),"1450px");}

  function actionRows(P,A,periods,current,previous){const actions=[];const platforms=P.meta.platforms.map(name=>{const c=preAgg(P.week.filter(r=>r.p===current&&r.pf===name)),p=preAgg(P.week.filter(r=>r.p===previous&&r.pf===name));return {name,c,p,delta:c.conversion-p.conversion};}).sort((a,b)=>a.delta-b.delta);const weak=platforms[0];if(weak&&Number.isFinite(weak.delta)&&weak.delta<0)actions.push({level:Math.abs(weak.delta)>=3?"P0":"P1",problem:`${weak.name}询单转化率下降`,evidence:`${weak.c.conversion.toFixed(1)}%，环比 ${pp(weak.delta)}；咨询 ${pct(change(weak.c.consult,weak.p.consult))}`,team:"客服、运营",action:"抽样未成交咨询，复盘流量、权益与话术",check:"下周转化率回到近4周均值"});
    const cur=A.issuesWeek.filter(r=>r.period===current),prev=A.issuesWeek.filter(r=>r.period===previous),names=[...new Set(cur.map(r=>r.issue))],risks=names.map(name=>{const count=sum(cur.filter(r=>r.issue===name),"count"),last=sum(prev.filter(r=>r.issue===name),"count");return {name,count,last,delta:count-last,rate:change(count,last)};}).sort((a,b)=>b.delta-a.delta),risk=risks[0];if(risk&&risk.delta>0)actions.push({level:risk.rate>=30&&risk.delta>=10?"P0":"P1",problem:`${risk.name}售后起数上升`,evidence:`${risk.count}起，较上周 +${risk.delta}起（${pct(risk.rate)}）`,team:"产品、仓储、客服",action:"下钻高发产品和问题环节，形成临时防控动作",check:"下周起数及每万元起数同时下降"});
    const pdd=preAgg(P.week.filter(r=>r.p===current&&r.pf==="拼多多"));if(pdd.days&&pdd.salesShareCoverage<90)actions.push({level:"P1",problem:"拼多多客服销售占比数据不完整",evidence:`本周有效完整率 ${pdd.salesShareCoverage.toFixed(1)}%，看板已显示“—”`,team:"数据填报、客服",action:"补齐每日店铺销售额或客服销售占比",check:"数据完整率达到90%以上"});
    if(!actions.length)actions.push({level:"P2",problem:"本周未识别到明显恶化项",evidence:"主要指标环比处于正常波动区间",team:"客服、运营",action:"继续跟踪近4周趋势",check:"下周继续保持稳定"});return actions;}

  function render(){const P=window.PRE_SALES_DATA,A=window.AFTER_SALES_DATA,root=$("#weeklyReviewBody");if(!root)return;if(!P||!A){root.innerHTML=`<article class="card loading-card"><div class="loading-dot"></div><h2>正在准备上周复盘…</h2></article>`;return;}
    const sets=[new Set(P.week.map(r=>r.p)),new Set(A.issuesWeek.map(r=>r.period)),new Set(A.salesWeek.filter(r=>Number(r.amount)>0).map(r=>r.period))],common=[...sets[0]].filter(p=>sets[1].has(p)&&sets[2].has(p)).sort(),current=common.at(-1),idx=common.indexOf(current),previous=common[idx-1],periods=common.slice(Math.max(0,idx-3),idx+1),yoyPeriod=lastYearPeriod(current),[start,end]=periodRange(current),curPre=preAgg(P.week.filter(r=>r.p===current)),prevPre=preAgg(P.week.filter(r=>r.p===previous)),yoyPreRows=P.week.filter(r=>r.p===yoyPeriod),yoyPre=yoyPreRows.length?preAgg(yoyPreRows):null,curAfter=afterAgg(A,current),prevAfter=afterAgg(A,previous),yoyAfterRows=A.issuesWeek.filter(r=>r.period===yoyPeriod),yoyAfter=yoyAfterRows.length?afterAgg(A,yoyPeriod):null;
    const preByPeriod=p=>preAgg(P.week.filter(r=>r.p===p)),afterByPeriod=p=>afterAgg(A,p),preTrend=periods.map(preByPeriod),afterTrend=periods.map(afterByPeriod),cards=[
      reviewCard("咨询人数",fmt.format(curPre.consult),curPre.consult,prevPre.consult,yoyPre?.consult,trend(periods,preTrend.map(x=>x.consult),v=>fmt.format(v)),"pct","售前工作量"),
      reviewCard("询单转化率",Number.isFinite(curPre.conversion)?curPre.conversion.toFixed(1)+"%":"—",curPre.conversion,prevPre.conversion,yoyPre?.conversion,trend(periods,preTrend.map(x=>x.conversion),v=>Number.isFinite(v)?v.toFixed(1)+"%":"—"),"pp","每日填报口径加权"),
      reviewCard("客服净销售额",money(curPre.sales),curPre.sales,prevPre.sales,yoyPre?.sales,trend(periods,preTrend.map(x=>x.sales),money),"pct","去退后销售额"),
      reviewCard("有效售后起数",fmt.format(curAfter.count),curAfter.count,prevAfter.count,yoyAfter?.count,trend(periods,afterTrend.map(x=>x.count),v=>fmt.format(v)),"pct","一条有效登记计1起"),
      reviewCard("每万元售后起数",Number.isFinite(curAfter.rate)?curAfter.rate.toFixed(3):"—",curAfter.rate,prevAfter.rate,yoyAfter?.rate,trend(periods,afterTrend.map(x=>x.rate),v=>Number.isFinite(v)?v.toFixed(3):"—"),"pct","售后起数 ÷ 电商销售额 × 10,000"),
      reviewCard("实际已打款",money(curAfter.paid),curAfter.paid,prevAfter.paid,yoyAfter?.paid,trend(periods,afterTrend.map(x=>x.paid),money),"pct","有明确打款时间的金额")
    ].join("");
    const actions=actionRows(P,A,periods,current,previous);
    root.innerHTML=`<section class="review-head panel"><div><span class="review-eyebrow">上一自然周</span><h2>客服售前售后复盘</h2><p>${start} 至 ${end} · ${current} · 环比 ${previous} · 同比 ${yoyPre||yoyAfter?yoyPeriod:"基期不完整"}</p></div><div class="review-actions"><button data-workspace="pre">查看售前明细</button><button data-workspace="after">查看售后明细</button></div></section><section class="review-kpis">${cards}</section><section class="card review-section"><div class="section-head"><div><h2>售前转化与服务效率</h2><p class="subtitle">每项同时展示本周值、环比和近4周趋势</p></div></div>${platformTable(P,periods,current,previous)}</section><section class="card review-section"><div class="section-head"><div><h2>售后问题变化</h2><p class="subtitle">按本周售后起数降序，同时检查占比、每万元起数和连续趋势</p></div></div>${issueTable(A,periods,current,previous)}</section><section class="card review-section"><div class="section-head"><div><h2>赔偿金额变化</h2><p class="subtitle">区分登记金额与实际打款，优先查看环比异常和大额记录</p></div></div>${compensationTable(A,periods,current,previous)}</section><section class="card review-section action-card"><div class="section-head"><div><h2>本周协同改善清单</h2><p class="subtitle">将数据变化转化为可执行动作，下周按验收指标复盘</p></div></div>${table(["优先级","问题","数据证据","协同角色","本周动作","下周验收"],actions.map(x=>`<tr><td><span class="tag ${x.level==="P0"?"red":"blue"}">${x.level}</span></td><td>${safe(x.problem)}</td><td>${safe(x.evidence)}</td><td>${safe(x.team)}</td><td>${safe(x.action)}</td><td>${safe(x.check)}</td></tr>`),"1250px")}</section><div class="notice review-notice">数据截止：售前 ${P.meta.sourceMax}，售后 ${A.meta.afterSalesMax}，电商销售 ${A.meta.salesMax}。本页只选择三类数据共同完整的自然周；同比基期不完整时显示“—”，并以近4周趋势辅助判断。</div>`;
  }
  window.WEEKLY_REVIEW_APP={render};
})();
